### ISSUE TITLE
[Bug] TypeError: TiktokenTokenizer.apply_chat_template() got an unexpected keyword argument 'reasoning_effort'

### ISSUE THREAD

**Issue by lshmouse** [sgl-project/sglang#9625]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

The openai server get following error when using completions api with sglang v0.5.1.post1-cu126 + grok2

The issue is introduced in https://github.com/sgl-project/sglang/pull/9043 which add an addition param in apply_chat_template call
```
[2025-08-26 10:36:30] INFO:     127.0.0.1:55274 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
[2025-08-26 10:38:03] Error in request: TiktokenTokenizer.apply_chat_template() got an unexpected keyword argument 'reasoning_effort'
Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/entrypoints/openai/serving_chat.py", line 223, in _apply_jinja_template
    prompt_ids = self.tokenizer_manager.tokenizer.apply_chat_template(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TiktokenTokenizer.apply_chat_template() got an unexpected keyword argument 'reasoning_effort'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/entrypoints/openai/serving_base.py", line 35, in handle_request
    adapted_request, processed_request = self._convert_to_internal_request(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sgl-workspace/sglang/python/sglang/srt/entrypoints/openai/serving_chat.py", line 107, in _convert_to_internal_request
    processed_messages = self._process_messages(request, is_multimodal)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sgl-workspace/sglang/python/sglang/srt/entrypoints/openai/serving_chat.py", line 172, in _process_messages
    result = self._apply_jinja_template(request, tools, is_multimodal)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sgl-workspace/sglang/python/sglang/srt/entrypoints/openai/serving_chat.py", line 242, in _apply_jinja_template
    prompt_ids = self.tokenizer_manager.tokenizer.apply_chat_template(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TiktokenTokenizer.apply_chat_template() got an unexpected keyword argument 'reasoning_effort'
[2025-08-26 10:38:03] INFO:     127.0.0.1:52002 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
```

<img width="1105" height="238" alt="Image" src="https://github.com/user-attachments/assets/e7017e13-e20c-4988-a826-bf2c4cb4c40a" />

### Reproduction

```
curl -X POST http://localhost:30000/v1/chat/completions \
    -H 'Content-Type:application/json' \
    -d '{"model": "base_model",
          "messages": [{"role": "user",
                        "content": "when 1+1=3?"}],
          "max_tokens": 1024,
          "stream": false}'
```

### Environment

```
#  python3 -m sglang.check_env 
Python: 3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H800
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.6, V12.6.68
CUDA Driver Version: 535.216.03
PyTorch: 2.8.0+cu126
sglang: 0.5.1.post1
sgl_kernel: 0.3.5
flashinfer_python: 0.2.11.post3
triton: 3.4.0
transformers: 4.55.2
torchao: 0.9.0+cu126
numpy: 2.3.2
aiohttp: 3.12.15
fastapi: 0.116.1
hf_transfer: 0.1.9
huggingface_hub: 0.34.4
interegular: 0.3.3
modelscope: 1.29.1
orjson: 3.11.2
outlines: 0.1.11
packaging: 25.0
psutil: 7.0.0
pydantic: 2.11.7
python-multipart: 0.0.20
pyzmq: 27.0.2
uvicorn: 0.35.0
uvloop: 0.21.0
vllm: Module Not Found
xgrammar: 0.1.23
openai: 1.99.1
tiktoken: 0.11.0
anthropic: 0.64.0
litellm: Module Not Found
decord: 0.6.0
NVIDIA Topology: 
```
