### PR TITLE
[CI Hot fix] Fix retired dp_attention CP accessors breaking every scheduler start

### PR DESCRIPTION
**Pull request by BBuf**
## Motivation

Main is currently broken: every scheduler start crashes with

```
ImportError: cannot import name 'get_attention_cp_size' from 'sglang.srt.layers.dp_attention'
```

`DefaultPoolConfigurator._compute_cell_size` unconditionally calls `get_glm_dsa_layer_split_effective_num_layers` (added in #29421), which imports `get_attention_cp_size` from `sglang.srt.layers.dp_attention`. #29421 was written against a base where those accessors existed, but the `get_parallel()` refactor (#30492 / #30493) retired them before #29421 merged — a semantic conflict, so the names no longer exist anywhere in the tree. This currently fails `test/registered/unit/model_executor/test_pool_configurator.py` and any CI job that launches a server (see the red scheduled full runs on main).

## Modifications

Switch the three files that still reference the retired accessors to the `get_parallel()` API:

- `sglang/srt/layers/cp/utils.py`: `get_attention_cp_size()` / `get_attention_cp_rank()` → `get_parallel().attn_cp_size` / `.attn_cp_rank`
- `sglang/srt/mem_cache/dsa_cache_layer_split.py`: `get_attention_cp_group()` → `get_parallel().attn_cp_group`
- `test/registered/unit/mem_cache/test_dsa_layer_split_broadcast.py`: same rename in the spawned-rank helper

No behavior change: the `get_parallel()` properties resolve to the same `parallel_state` getters the old wrappers delegated to.

cc @merrymercy @Fridge003

🤖 Generated with [Claude Code](https://claude.com/claude-code)

---
### CI States

Latest PR Test (Base): :x: [Run #29020960665](https://github.com/sgl-project/sglang/actions/runs/29020960665)
Latest PR Test (Extra): :x: [Run #29020960404](https://github.com/sgl-project/sglang/actions/runs/29020960404)

### CODE REVIEW

**Comment by hirakunaramuka2** [comment]
Heads up — this looks like it's fixing the same thing as #30653 from @mmangkad (which already has CI further along).

**Comment by BBuf** [comment]
> Heads up — this looks like it's fixing the same thing as #30653 from @mmangkad (which already has CI further along).

Ok, I will close it.
