### PR TITLE
fix: adding teacache.params back to sampling params as intended

### PR DESCRIPTION
**Pull request by dougyster**
## Motivation

Currently, adding enable_teacache=true fails with 'Req' object has no attribute 'teacache_params'. This bug was introduced in PR #19964 which intended to remove teacache_params from the request body so fallback to sampling params to be handled, but teacache_params were not on sampling params.

Also added teacache params for Wan 2.2 using the Wan2.1 14B coefficients as a proxy so that enable_teacache actually takes effect.

## Modifications

Adding teacache_params back to sampling params and added teacache_params: to class Wan2_2_Base_SamplingParams.

## Accuracy Tests

```
python3 -m
  sglang.multimodal_gen.runtime.entrypoints.cli.main
  serve \
    --model-path Wan-AI/Wan2.2-T2V-A14B-Diffusers \
    --dit-layerwise-offload \
    --host 0.0.0.0 --port 8080

  Request:
  curl "http://localhost:8080/v1/videos" \
    -F "prompt=A dog running through a park" \
    -F "size=832x480" \
    -F "num_frames=81" \
    -F "fps=24" \
    -F "num_inference_steps=50" \
    -F "guidance_scale=5.0" \
    -F "negative_prompt=blurry, low quality, distorted"
   \
    -F "seed=42" \
    -F "enable_teacache=true"
```

https://github.com/user-attachments/assets/ac55e858-feb0-457b-8ac9-73173c2a0b5a

## Checklist

- [Done ] Format your code according to the [Format code with pre-commit](https://docs.sglang.io/developer_guide/contribution_guide.html#format-code-with-pre-commit).
- [ Done] Add unit tests according to the [Run and add unit tests](https://docs.sglang.io/developer_guide/contribution_guide.html#run-and-add-unit-tests).
- [ Done] Update documentation according to [Write documentations](https://docs.sglang.io/developer_guide/contribution_guide.html#write-documentations).
- [ Done] Provide accuracy and speed benchmark results according to [Test the accuracy](https://docs.sglang.io/developer_guide/contribution_guide.html#test-the-accuracy) and [Benchmark the speed](https://docs.sglang.io/developer_guide/contribution_guide.html#benchmark-the-speed).
- [ Done] Follow the SGLang code style [guidance](https://docs.sglang.io/developer_guide/contribution_guide.html#code-style-guidance).

## Review Process

1. Ping Merge Oncalls to start the PR flow. See the [PR Merge Process](https://github.com/sgl-project/sglang/blob/main/.github/MAINTAINER.md#pull-request-merge-process).
2. Get approvals from [CODEOWNERS](https://github.com/sgl-project/sglang/blob/main/.github/CODEOWNERS) and other reviewers.
3. Trigger CI tests with [comments](https://docs.sglang.io/developer_guide/contribution_guide.html#how-to-trigger-ci-tests) or contact authorized users to do so.
   - `/tag-run-ci-label`, `/rerun-failed-ci`, `/tag-and-rerun-ci`
4. After green CI and required approvals, ask Merge Oncalls to merge.

### CODE REVIEW

**Review by mickqian — COMMENTED** [review]
could we modify a testcase to guard this model?

**Review by mickqian — APPROVED** [review]
