### ISSUE TITLE
[Bug] ImportError: cannot import name 'ActionFind' from 'openai.types.responses.response_function_web_search'

### ISSUE THREAD

**Issue by ping1jing2** [sgl-project/sglang#8886]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

VLLM Dependency Test / vllm-dependency-test (pull_request)

ImportError: cannot import name 'ActionFind' from 'openai.types.responses.response_function_web_search'

### Reproduction

all PRs have encounteered this error in the `VLLM Dependency Test / vllm-dependency-test (pull_request)`, i think this is caused by #8837 . Now we require ["openai>=1.99.1"](https://github.com/sgl-project/sglang/pull/8837/files#diff-1a45bd938160f7761769e7b6fbc819d1cc7f84ce37f1a6a23ef83cc4e214abc8R100), but vllm change the version `2025-08-07T01:24:03.7456528Z Collecting openai<=1.90.0,>=1.87.0 (from vllm==0.10.0)`

see [vllm-dependency-test.yml](https://github.com/sgl-project/sglang/blob/main/.github/workflows/vllm-dependency-test.yml)
```yaml
      - name: Install dependencies
        run: |
          bash scripts/ci_install_dependency.sh    # openai>=1.99.1
          pip install "vllm==0.10.0"                       # Downloading openai-1.90.0-py3-none-any.whl.metadata (26 kB)
          pip install "bitsandbytes>=0.44.0"
          pip3 install torch==2.8.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/test/cu126
```

more details can be search in the [CI log](https://productionresultssa12.blob.core.windows.net/actions-results/e106abeb-efc3-49b9-a7f7-0a9ea03cd954/workflow-job-run-d9a4cd43-40ae-54bd-9f97-197ca5f33ddd/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-08-07T02%3A59%3A05Z&sig=24NPPtKPXtVymC9MIJPr8B7ecrCxfaUzRJuyaEFnBpc%3D&ske=2025-08-07T12%3A46%3A04Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-08-07T00%3A46%3A04Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-08-07T02%3A49%3A00Z&sv=2025-05-05)

### Environment

CI

**Comment by ping1jing2** [comment]
#8983 and #9012 had solved it.
