### PR TITLE
[MLX] Fix startup crash when reporting preloaded weights

### LINKED ISSUE #37031: [Bug] MLX server crashes because MlxModelRunnerStub has no loader
### Checklist

- [x] I searched related issues but found no solution.
- [x] The bug persists in the latest version.
- [x] Issues without environment info and a minimal reproducible demo are hard to resolve and may receive no feedback.
- [x] If this is not a bug report but a general question, please start a discussion at https://github.com/sgl-project/sglang/discussions. Otherwise, it will be closed.
- [x] Please use English. Otherwise, it will be closed.

### Describe the bug

I'm getting an MLX startup crash on current main and (`4d53767b09429c67a4137352c762372923853eb6`). It looks like a regression from #34053.

The scheduler reads `preloaded_weights_bytes`. The MLX stub inherits this property from `ModelRunner`, where it reads `self.loader.preloaded_weights_bytes`. But `MlxModelRunnerStub` does not create a Torch loader.

Expected: the server starts.

Actual:

```text
Scheduler.init_target_memory_pool
  -> BaseTpWorker.preloaded_weights_bytes
  -> ModelRunner.preloaded_weights_bytes
AttributeError: 'MlxModelRunnerStub' object has no attribute 'loader'
```

I have a minimal fix and regression test ready: the MLX stub should report 0 preloaded Torch weight bytes.

### Reproduction

``bash
SGLANG_USE_MLX=1 uv run --python 3.12 python -m sglang.launch_server \
  --model HuggingFaceTB/SmolLM2-135M-Instruct \
  --max-total-tokens 4096 \
  --cuda-graph-backend-decode disabled \
  --cuda-graph-backend-prefill disabled \
  --host 127.0.0.1 \
  --port 43440
```

### Environment

``text
Python: 3.12.9 (main, Feb 12 2025, 15:09:19) [Clang 19.1.6 ]
MPS available: True
macOS Version: 15.6.1
macOS Build: 24G90
Apple Silicon: Apple M4 Pro
Unified Memory: 24.0 GB
CPU Cores (Total): 12
CPU Cores (Performance): 8
CPU Cores (Efficiency): 4
Metal Support: Metal 3
GPU Cores: 16
PyTorch: 2.13.0
sglang: 0.5.19.dev649+g4d53767b0
sglang-kernel: Module Not Found
flashinfer_python: Module Not Found
flashinfer_cubin: Module Not Found
flashinfer_jit_cache: Module Not Found
triton: Module Not Found
transformers: 5.12.1
torchao: Module Not Found
numpy: 2.3.5
aiohttp: 3.14.3
fastapi: 0.141.1
huggingface_hub: 1.29.0
interegular: 0.3.3
modelscope: 1.39.1
orjson: 3.12.0
outlines: 0.1.11
packaging: 26.3
psutil: 7.2.2
pydantic: 2.13.5
python-multipart: 0.0.32
pyzmq: 27.2.0
uvicorn: 0.52.4
uvloop: 0.22.1
vllm: Module Not Found
xgrammar: 0.2.1
openai: 2.6.1
tiktoken: 0.14.0
anthropic: 1.2.0
litellm: Module Not Found
torchcodec: 0.15.0
mlx: 0.32.2
mlx-lm: 0.31.3
mlx-metal: 0.32.2
ulimit soft: 1048575
```

### PR DESCRIPTION
**Pull request by ainergiz**
## Motivation

I hit an MLX startup crash after #34053. The scheduler reads `preloaded_weights_bytes`, but the inherited property accesses `self.loader`. `MlxModelRunnerStub` intentionally has no Torch `ModelLoader`.

Fixes #37031.

## Modifications

- Report 0 bytes for the base Torch loader accounting hook.
- Document why this is correct: the native MLX runner materializes weights before sizing its own KV pool.
- Add a regression test using the registered-test `CustomTestCase`.

## Accuracy Tests

Not applicable. Model outputs are unchanged.

## Speed Tests and Profiling

Not applicable. The inference path is unchanged.

## Tests

- `SGLANG_USE_MLX=1 uv run --python 3.12 python -m pytest -q test/registered/unit/hardware_backend/mlx` — 221 passed, 4 skipped, 23 subtests passed
- `uvx pre-commit run --files ...` — passed
- Manual MLX startup and generation with `HuggingFaceTB/SmolLM2-135M-Instruct`

## Checklist

- [x] Formatting and pre-commit checks pass.
- [x] Added a unit test.
- [x] No documentation change is needed.
- [x] Accuracy and speed benchmarks are not applicable.
- [x] Followed the SGLang code style guidance.

---
### CI States

Latest PR Test (Base): :x: [Run #33253560035](https://github.com/sgl-project/sglang/actions/runs/33253560035)
Latest PR Test (Extra): :x: [Run #33253559941](https://github.com/sgl-project/sglang/actions/runs/33253559941)
Latest PR Test (AMD ROCm 7.2): :x: [Run #33253560015](https://github.com/sgl-project/sglang/actions/runs/33253560015)

### CODE REVIEW

**Review by yeahdongcn — APPROVED** [review]

**Comment by yeahdongcn** [comment]
The MLX CI has passed: https://github.com/sgl-project/sglang/actions/runs/33253560006/job/99213210526?pr=37035. @Kangyan-Zhou please merge it when you have a chance. Thanks!
