### PR TITLE
[Cherry pick to release/v0.5.15] Fix NVFP4 online quantization

### PR DESCRIPTION
**Pull request by b8zhong**
`test/registered/backends/test_flashinfer_trtllm_gen_moe_backend.py`
`AttributeError: 'NvFp4OnlineConfig' object has no attribute 'dequant_fp4_to_fp8'`

It's broken by https://github.com/sgl-project/sglang/pull/27867

---
### CI States

Latest PR Test (Base): :x: [Run #28869009529](https://github.com/sgl-project/sglang/actions/runs/28869009529)
Latest PR Test (Extra): :no_entry_sign: [Run #28869008915](https://github.com/sgl-project/sglang/actions/runs/28869008915)

### CODE REVIEW

**Comment by b8zhong** [comment]
/rerun-test test/registered/backends/test_flashinfer_trtllm_gen_moe_backend.py

**Review by Fridge003 — APPROVED** [review]
