### PR TITLE
[Fix] Correct W4AFP8 DeepEP scaling and mode-specific dtypes

### LINKED ISSUE #33660: [Bug] W4AFP8 + DeepEP crashes at first inference: TypeError "missing 1 required positional argument: 'routed_scaling_factor'"
### Describe the bug

When serving a W4AFP8-quantized DeepSeek-V2 architecture model (GLM-5.2) with `--quantization w4afp8 --moe-a2a-backend deepep` (normal mode), the server boots, loads weights, and completes DeepGEMM JIT pre-compilation successfully, then **every DP/TP/EP rank crashes simultaneously on the first inference request** with:

```
TypeError: dynamic_func() missing 1 required positional argument: 'routed_scaling_factor'
```

The failure is in the W4AFP8 + DeepEP-normal MoE combine path. This is a regression introduced by #23754.

### Reproduction

Image: `lmsysorg/sglang:v0.5.16-cu130` (also reproducible on current `main`).
Hardware: 8× H200 (single node). Model: `PhalaCloud/GLM-5.2-W4AFP8` (served as `zai-org/GLM-5.2-FP8`).

Minimal command (EAGLE/MTP and hicache from the original run are **not** required to trigger the bug — the target model's MoE hits it on its own):

```bash
python3 -m sglang.launch_server \
  --model-path PhalaCloud/GLM-5.2-W4AFP8 \
  --quantization w4afp8 \
  --tp 8 --dp 4 --ep 8 \
  --enable-dp-attention --enable-dp-attention-local-control-broadcast \
  --moe-a2a-backend deepep \
  --served-model-name zai-org/GLM-5.2-FP8 \
  --host 0.0.0.0 --port 8889
```

Then send any single completion request. The crash fires immediately (no output produced).

Full original launch command (with EAGLE MTP + hicache, from the benchmark run that surfaced this):

```bash
python3 -m sglang.launch_server \
  --model-path /models/PhalaCloud/GLM-5.2-W4AFP8 --quantization w4afp8 \
  --host 0.0.0.0 --port 8889 --tp 8 --dp 4 --ep 8 \
  --enable-dp-attention --enable-dp-attention-local-control-broadcast \
  --tokenizer-worker-num 8 --dist-init-addr 127.0.0.1:10888 \
  --numa-node 0 0 0 0 1 1 1 1 \
  --moe-a2a-backend deepep --chunked-prefill-size 32768 \
  --tool-call-parser glm47 --reasoning-parser glm45 \
  --mem-fraction-static 0.75 --max-running-requests 48 --context-length 500000 \
  --kv-cache-dtype fp8_e4m3 --allow-auto-truncate --enable-metrics \
  --enable-cache-report --enable-hierarchical-cache --hicache-size 128 \
  --speculative-algorithm EAGLE --speculative-num-steps 3 \
  --speculative-eagle-topk 1 --speculative-num-draft-tokens 4 \
  --schedule-policy dfs-weight --served-model-name zai-org/GLM-5.2-FP8
```

### Expected behavior

Server serves requests. `routed_scaling_factor` from the model config (2.5 for GLM-5.2 / DeepSeek-V3.x) should be folded into the topk weights inside `deepep_post_reorder_triton_kernel`.

### Actual behavior

All 8 ranks crash at the same timestamp on first inference (server boot was ~10 min earlier; DeepGEMM JIT pre-compile completed normally). One representative traceback (dp1/tp2/ep2); the other 7 ranks fail identically:

<details><summary>Full traceback (click to expand)</summary>

```
[2026-08-04 14:43:00 DP1 TP2 EP2] Scheduler hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 4639, in run_scheduler_process
    scheduler.run_event_loop()
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1500, in run_event_loop
    dispatch_event_loop(self)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 4490, in dispatch_event_loop
    scheduler.event_loop_overlap()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1601, in event_loop_overlap
    batch_result = self.run_batch(batch)
  File "/sgl-workspace/sglang/python/sglang/srt/utils/nvtx_utils.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 3351, in run_batch
    batch_result = self.model_worker.forward_batch_generation(
  File "/sgl-workspace/sglang/python/sglang/srt/speculative/eagle_worker_v2.py", line 1130, in forward_batch_generation
    batch_output = self.target_worker.forward_batch_generation(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 564, in forward_batch_generation
    out = self.model_runner.forward(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1277, in forward
    output = self._forward_raw(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1463, in _forward_raw
    ret = self.eager_runner.execute(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/runner/eager_runner.py", line 203, in execute
    return self._execute_extend(forward_batch, pp_proxy_tensors)
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/runner/eager_runner.py", line 332, in _execute_extend
    ret = model_runner.model.forward(
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 2871, in forward
    hidden_states = self.model(
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 2603, in forward
    hidden_states, residual, topk_indices = layer(
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 2275, in forward
    hidden_states = self.mlp(
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 919, in forward
    return self.forward_deepep(
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1399, in forward_deepep
    final_hidden_states = self.experts(
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/moe/ep_moe/layer.py", line 175, in forward
    return self.forward_impl(hidden_states, topk_output)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/moe/ep_moe/layer.py", line 192, in forward_impl
    combine_input = self.run_moe_core(dispatch_output)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/moe/ep_moe/layer.py", line 221, in run_moe_core
    output = self.forward_cutlass_w4afp8(dispatch_output)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/moe/ep_moe/layer.py", line 262, in forward_cutlass_w4afp8
    return self.quant_method.apply_deepep_normal(
  File "/sgl-workspace/sglang/python/sglang/srt/layers/quantization/w4afp8.py", line 384, in apply_deepep_normal
    return cutlass_w4a8_moe_deepep_normal(
  File "/sgl-workspace/sglang/python/sglang/srt/layers/moe/cutlass_w4a8_moe.py", line 420, in cutlass_w4a8_moe_deepep_normal
    deepep_post_reorder_triton_kernel[(num_tokens,)](
  File "/usr/local/lib/python3.12/dist-packages/triton/runtime/jit.py", line 370, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/triton/runtime/jit.py", line 710, in run
    bound_args, specialization, options = binder(*args, **kwargs)
TypeError: dynamic_func() missing 1 required positional argument: 'routed_scaling_factor'
```

</details>

### Environment

- **SGLang**: `lmsysorg/sglang:v0.5.16-cu130` (release); also confirmed on current `main`.
- **Model**: `PhalaCloud/GLM-5.2-W4AFP8` (DeepSeek-V2 arch, 256 routed experts, `routed_scaling_factor=2.5`), served as `zai-org/GLM-5.2-FP8`.
- **Quantization**: `w4afp8`, MoE runner auto-resolved to `cutlass`.
- **Parallelism**: TP=8, DP=4, EP=8, `--enable-dp-attention`, `--moe-a2a-backend deepep` (`deepep_mode=auto` → normal for prefill).
- **Hardware**: 8× NVIDIA H200 (single node).
- **Speculative**: EAGLE MTP, draft also w4afp8 (not required to repro).

### PR DESCRIPTION
**Pull request by CyberSecurityErial**
## Motivation

W4AFP8 with DeepEP had two independent failures in the same normal/prefill path.

First, `cutlass_w4a8_moe_deepep_normal` called `deepep_post_reorder_triton_kernel` without the required `routed_scaling_factor`, causing the original first-request `TypeError` in #33660. The model forward applies routed scaling after the cross-rank DeepEP combine, so this rank-local reduction must receive the neutral value `1.0`; using the model factor here would scale twice.

After the first fix, the reporter reproduced a second failure on 4xH200: DeepEP `intranode.cu:926` reported `Unsupported type`. That line is the normal **combine** dtype switch, not an INT4-weight dispatch site; DeepEP only transports activations and its normal combine accepts BF16. The actual problem was SGLang's dtype selection:

- W4AFP8 normal/prefill requantizes BF16 activations with checkpoint static scales, so its DeepEP payload must remain BF16.
- W4AFP8 low-latency/decode consumes DeepEP FP8 activations together with per-token-group scales, so that payload must remain FP8.
- With `--deepep-mode auto`, the previous global default selected FP8 for both implementations. The normal W4AFP8 path discarded the returned FP8 scale; a zero-token expert rank then returned an FP8 tensor directly to DeepEP's BF16-only normal combine, producing the reported assertion. Globally forcing BF16 would fix prefill but break low-latency decode.

Fixes #33660.

## Modifications

- Pass neutral `routed_scaling_factor=1.0` to the W4AFP8 DeepEP-normal post-reorder kernel.
- Let each concrete DeepEP implementation resolve a mode-specific dispatcher dtype.
- Configure W4AFP8 as normal=`bf16`, low-latency=`fp8`, including `auto` mode and TBO wrappers through the existing dispatcher configuration propagation.
- Add explicit guards for invalid normal and low-latency payloads, avoiding silent scale loss.
- Add CPU regressions for the kernel argument, per-mode dtype resolution, zero-token normal behavior, and missing low-latency scales.

## Accuracy Tests

The original routed-scale regression was run in the H20 SGLang image and passed before this update. The issue reporter independently confirmed that it fixes the original missing-argument `TypeError`.

For the mode-specific dtype update, the available H20s are serving traffic and the exact W4AFP8 checkpoint is not locally available, so a full model E2E was not run. The following non-GPU checks pass on current `main`:

```text
Black: passed
isort: passed
Ruff (F401, F821, UP037): passed
Python compilation: passed
scripts/ci/check_registered_tests.py: passed
Rebase/diff checks: passed
```

The new CPU regression is registered in `base-a-test-cpu`; an H200 retest is requested from the reporter.

## Speed Tests and Profiling

Not applicable. This corrects payload format and a required kernel argument without changing the MoE algorithm.

## Checklist

- [x] Rebased onto current `main`.
- [x] Formatted with repository-compatible tools.
- [x] Added targeted CPU regression coverage.
- [x] Documentation is not affected.
- [x] No public API behavior is changed.

---
### CI States

Latest PR Test (Base): :x: [Run #31152633812](https://github.com/sgl-project/sglang/actions/runs/31152633812)
Latest PR Test (Extra): :x: [Run #31350741874](https://github.com/sgl-project/sglang/actions/runs/31350741874)

### CODE REVIEW

**Comment by CyberSecurityErial** [comment]
Update: the 16 previous failures were all gate cascades caused by the missing run-ci label; no test body ran. I have rebased this PR onto the latest main (a5888c956f). The regression test passed before the rebase; the unchanged diff now also passes test-registration, Python compile, and diff checks on the updated branch.

@b8zhong, could you please review and run /tag-and-rerun-ci? I do not have permission to add the label.

@thangquang09, could you also validate this branch on the original GLM-5.2-W4AFP8 + DeepEP setup when convenient?

**Comment by CyberSecurityErial** [comment]
Updated the PR with the second W4AFP8 + DeepEP fix: normal/prefill now dispatches BF16, while low-latency/decode keeps FP8 plus scales. The branch is rebased on current main at 7fb9202aa5. The current red gates only report the missing run-ci label; no test body ran. @b8zhong, could you please run /tag-and-rerun-ci? @thangquang09, an H200 retest of the updated branch would be very helpful.

**Review by BBuf — APPROVED** [review]

**Comment by BBuf** [comment]
Can we clean up the tests?
