### PR TITLE
Fix quant_method access before create

### PR DESCRIPTION
**Pull request by qhsc**
## Motivation

Fix quant_method access before create introduced in #9269.
```bash
File "/root/fork-sgl/python/sglang/srt/layers/moe/fused_moe_triton/layer.py", line 196, in __init__
    if self.quant_method.__class__.__name__ in (
       ^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.12.11/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1962, in __getattr__
    raise AttributeError(
AttributeError: 'DeepEPMoE' object has no attribute 'quant_method'
```
## Checklist

- [ ] Format your code according to the [Format code with pre-commit](https://docs.sglang.ai/developer_guide/contribution_guide.html#format-code-with-pre-commit).
- [ ] Add unit tests according to the [Run and add unit tests](https://docs.sglang.ai/developer_guide/contribution_guide.html#run-and-add-unit-tests).
- [ ] Update documentation according to [Write documentations](https://docs.sglang.ai/developer_guide/contribution_guide.html#write-documentations).
- [ ] Provide accuracy and speed benchmark results according to [Test the accuracy](https://docs.sglang.ai/developer_guide/contribution_guide.html#test-the-accuracy) and [Benchmark the speed](https://docs.sglang.ai/developer_guide/contribution_guide.html#benchmark-the-speed).

### CODE REVIEW

**Comment by hnyls2002** [comment]
Thanks @qhsc! FusedMoE init was refactored so quant_method is set before create_weights now, so this
  ordering issue is gone on main - closing. Please reopen if it still shows up.
