### PR TITLE
[Bug Fix] Fix Glm4vVisionBlock norm

### PR DESCRIPTION
**Pull request by sdpkjc**
## Motivation

This PR fixes a runtime crash in `Glm4vVisionBlock` when running vision prefill. After #9709, `Qwen2_5_VisionBlock` calls `norm2(x2d, residual=attn2d)` and expects a residual-aware interface that returns `(norm2d, after_add2d)`. `Glm4vVisionBlock` was still overriding `norm1/norm2` with `Glm4vRMSNorm`, whose `forward` did not accept `residual`, causing a `TypeError` and the worker to die.

**Minimum Reproduce**

```python
import sglang as sgl
from PIL import Image
from io import BytesIO
import requests
from transformers import AutoTokenizer


model_path = "zai-org/GLM-4.1V-9B-Thinking"
image_url = "https://github.com/sgl-project/sglang/blob/main/test/lang/example_image.png?raw=true"

if __name__ == "__main__":
    image = Image.open(BytesIO(requests.get(image_url).content))

    tokenizer = AutoTokenizer.from_pretrained(model_path)
    messages = [{"role": "user", "content": [{"type": "image"}, {"type": "text", "text": "What's shown here?"}]}]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    engine = sgl.Engine(model_path=model_path)
    ret = engine.generate(prompt=prompt, image_data=[image])

    print("\n=== Prompt ===\n", prompt)
    print("\n=== Completion ===\n", ret["text"])

'''
ERROR INFO:
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/models/qwen2_5_vl.py", line 188, in forward
    x_norm_2d, x_after_add_2d = self.norm2(x2d, residual=attn2d)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: Glm4vRMSNorm.forward() got an unexpected keyword argument 'residual'
'''
```

**Packages Versions:**

* sglang: 0.5.2rc0
* torch: 2.8.0
* transformers: 4.56.0
* model: `GLM-4.1V-9B-Thinking`

**Bug cause:**

* `Qwen2_5_VisionBlock` (post-#9709) reshapes to 2D and invokes `self.norm2(..., residual=...)`.
* `Glm4vVisionBlock` overrides `self.norm1/self.norm2` with `Glm4vRMSNorm`, whose `forward(x)` signature lacked the `residual` kwarg.
* When the parent `forward()` path executed, Python raised `TypeError` due to the unexpected keyword.

## Modifications

* Do **not** override `self.norm1` / `self.norm2` in `Glm4vVisionBlock.__init__`.
* Rely on the parent `Qwen2_5_VisionBlock`’s `RMSNorm` modules introduced in #9709, which natively support the `residual` path and 2D reshape semantics.

This is the smallest change that fully restores compatibility and matches the new canonical behavior.

## Accuracy Tests

After the fix, the same script can run successfully, and the output is as expected.

## Checklist

- [x] Format your code according to the [Format code with pre-commit](https://docs.sglang.ai/developer_guide/contribution_guide.html#format-code-with-pre-commit).
- [ ] Add unit tests according to the [Run and add unit tests](https://docs.sglang.ai/developer_guide/contribution_guide.html#run-and-add-unit-tests).
- [ ] Update documentation according to [Write documentations](https://docs.sglang.ai/developer_guide/contribution_guide.html#write-documentations).
- [ ] Provide accuracy and speed benchmark results according to [Test the accuracy](https://docs.sglang.ai/developer_guide/contribution_guide.html#test-the-accuracy) and [Benchmark the speed](https://docs.sglang.ai/developer_guide/contribution_guide.html#benchmark-the-speed).

### CODE REVIEW

**Comment by vincentzed** [comment]
Thank you for the fix @sdpkjc I can try to test it later too

**Comment by vincentzed** [comment]
@sdpkjc Is the accuracy the same?
If you launch the server on `main` (without fix) and on this branch, then you run the below:
```python
python benchmark/mmmu/bench_sglang.py --port 30000 --concurrency 16
```
Do you get ~ the same score? In Q2.5 the RMSNorm patch was OK but hopefully it doesn't break GLM4.1V

**Comment by sdpkjc** [comment]
@vincentzed On the main branch, launching the GLM4.1V server crashes, so I can’t run the benchmark there. I can roll back to v0.5.1 and run the same benchmark to compare with this PR. v0.5.1 was released before #9709 and doesn’t have the crash.

**Comment by sdpkjc** [comment]
```text
PR#9884 (NOW)

Evaluating...
{'Accounting': {'acc': 0.267, 'num': 30},
 'Agriculture': {'acc': 0.467, 'num': 30},
 'Architecture_and_Engineering': {'acc': 0.2, 'num': 30},
 'Art': {'acc': 0.3, 'num': 30},
 'Art_Theory': {'acc': 0.167, 'num': 30},
 'Basic_Medical_Science': {'acc': 0.467, 'num': 30},
 'Biology': {'acc': 0.4, 'num': 30},
 'Chemistry': {'acc': 0.167, 'num': 30},
 'Clinical_Medicine': {'acc': 0.133, 'num': 30},
 'Computer_Science': {'acc': 0.167, 'num': 30},
 'Design': {'acc': 0.233, 'num': 30},
 'Diagnostics_and_Laboratory_Medicine': {'acc': 0.3, 'num': 30},
 'Economics': {'acc': 0.267, 'num': 30},
 'Electronics': {'acc': 0.167, 'num': 30},
 'Energy_and_Power': {'acc': 0.333, 'num': 30},
 'Finance': {'acc': 0.167, 'num': 30},
 'Geography': {'acc': 0.3, 'num': 30},
 'History': {'acc': 0.3, 'num': 30},
 'Literature': {'acc': 0.233, 'num': 30},
 'Manage': {'acc': 0.167, 'num': 30},
 'Marketing': {'acc': 0.167, 'num': 30},
 'Materials': {'acc': 0.267, 'num': 30},
 'Math': {'acc': 0.133, 'num': 30},
 'Mechanical_Engineering': {'acc': 0.3, 'num': 30},
 'Music': {'acc': 0.233, 'num': 30},
 'Overall': {'acc': 0.264, 'num': 900},
 'Overall-Art and Design': {'acc': 0.233, 'num': 120},
 'Overall-Business': {'acc': 0.207, 'num': 150},
 'Overall-Health and Medicine': {'acc': 0.307, 'num': 150},
 'Overall-Humanities and Social Science': {'acc': 0.3, 'num': 120},
 'Overall-Science': {'acc': 0.267, 'num': 150},
 'Overall-Tech and Engineering': {'acc': 0.271, 'num': 210},
 'Pharmacy': {'acc': 0.3, 'num': 30},
 'Physics': {'acc': 0.333, 'num': 30},
 'Psychology': {'acc': 0.333, 'num': 30},
 'Public_Health': {'acc': 0.333, 'num': 30},
 'Sociology': {'acc': 0.333, 'num': 30}}
eval out saved to ./val_sglang.json
Overall accuracy: 0.264
```

```text
Tag v0.5.1

Evaluating...
{'Accounting': {'acc': 0.2, 'num': 30},
 'Agriculture': {'acc': 0.333, 'num': 30},
 'Architecture_and_Engineering': {'acc': 0.267, 'num': 30},
 'Art': {'acc': 0.367, 'num': 30},
 'Art_Theory': {'acc': 0.2, 'num': 30},
 'Basic_Medical_Science': {'acc': 0.3, 'num': 30},
 'Biology': {'acc': 0.467, 'num': 30},
 'Chemistry': {'acc': 0.233, 'num': 30},
 'Clinical_Medicine': {'acc': 0.267, 'num': 30},
 'Computer_Science': {'acc': 0.133, 'num': 30},
 'Design': {'acc': 0.233, 'num': 30},
 'Diagnostics_and_Laboratory_Medicine': {'acc': 0.267, 'num': 30},
 'Economics': {'acc': 0.3, 'num': 30},
 'Electronics': {'acc': 0.133, 'num': 30},
 'Energy_and_Power': {'acc': 0.267, 'num': 30},
 'Finance': {'acc': 0.233, 'num': 30},
 'Geography': {'acc': 0.167, 'num': 30},
 'History': {'acc': 0.167, 'num': 30},
 'Literature': {'acc': 0.4, 'num': 30},
 'Manage': {'acc': 0.233, 'num': 30},
 'Marketing': {'acc': 0.233, 'num': 30},
 'Materials': {'acc': 0.167, 'num': 30},
 'Math': {'acc': 0.267, 'num': 30},
 'Mechanical_Engineering': {'acc': 0.3, 'num': 30},
 'Music': {'acc': 0.333, 'num': 30},
 'Overall': {'acc': 0.266, 'num': 900},
 'Overall-Art and Design': {'acc': 0.283, 'num': 120},
 'Overall-Business': {'acc': 0.24, 'num': 150},
 'Overall-Health and Medicine': {'acc': 0.287, 'num': 150},
 'Overall-Humanities and Social Science': {'acc': 0.283, 'num': 120},
 'Overall-Science': {'acc': 0.293, 'num': 150},
 'Overall-Tech and Engineering': {'acc': 0.229, 'num': 210},
 'Pharmacy': {'acc': 0.433, 'num': 30},
 'Physics': {'acc': 0.333, 'num': 30},
 'Psychology': {'acc': 0.367, 'num': 30},
 'Public_Health': {'acc': 0.167, 'num': 30},
 'Sociology': {'acc': 0.2, 'num': 30}}
eval out saved to ./val_sglang.json
Overall accuracy: 0.266
```

**Comment by JustinTong0323** [comment]
> ```
> PR#9884 (NOW)
> ...
> Overall accuracy: 0.264
> ```
> 
> ```
> Tag v0.5.1
> ...
> Overall accuracy: 0.266
> ```

The accuracy is so low, due to the max tokens limitation. Next time when testing the reasoning model we should set the max token to a very high value, but it's ok for now.

**Review by JustinTong0323 — APPROVED** [review]

**Comment by vincentzed** [comment]
Thanks!
