### PR TITLE
Fix DFlash mamba verify init ordering

### PR DESCRIPTION
**Pull request by mmangkad**
## Summary

Fixes a DFlash startup crash introduced in #29218. The new code checked the target `ModelRunner.attn_backend` inside `DFlashWorkerV2.__init__`, but the backend is not ready yet at that point. Before this, the server could fail during scheduler startup with:

```text
AttributeError: 'ModelRunner' object has no attribute 'attn_backend'
```

After moving the mamba verify-commit check until after attention backend init, the DFlash worker no longer reads the target backend too early.

---
### CI States

Latest PR Test (Base): :no_entry_sign: [Run #29057403869](https://github.com/sgl-project/sglang/actions/runs/29057403869)
Latest PR Test (Extra): :x: [Run #29057403746](https://github.com/sgl-project/sglang/actions/runs/29057403746)

### CODE REVIEW

File: python/sglang/srt/speculative/dflash_worker_v2.py [hunk 1]
```diff
@@ -286,6 +281,19 @@ def alloc_memory_pool(
...
+                self.model_runner.attn_backend,
+                "update_mamba_state_after_mtp_verify",
+            )
+        )
+
+    def _needs_mamba_verify_commit(self) -> bool:
+        assert (
+            self._need_mamba_verify_commit is not None
+        ), "_needs_mamba_verify_commit called before init_attention_backends"
+        return self._need_mamba_verify_commit
```
Comment (kpham-sgl) [inline python/sglang/srt/speculative/dflash_worker_v2.py]: why is this function needed?

**Review by kpham-sgl — COMMENTED** [review]
Sorry, I missed this when reviewing https://github.com/sgl-project/sglang/pull/29218. Thanks for catching

File: python/sglang/srt/speculative/dflash_worker_v2.py (hunk 1 above)
Comment (mmangkad) [reply python/sglang/srt/speculative/dflash_worker_v2.py]: It’s just guarding against an init-order regression, but I think we can remove it here

**Comment by kpham-sgl** [comment]
/rerun-test test/registered/quant/test_kimi_k26_nvfp4_dflash.py

**Comment by kpham-sgl** [comment]
Safe to merge

**Comment by thanhhao98** [comment]
Thanks @mmangkad for fixing that bug !
