### PR TITLE
fix: guard self.model access in Qwen3VLMoeForConditionalGeneration.load_weights

### LINKED ISSUE #23063: [Bug] [Encode Prefill Disaggregation] [Func] [SDV] Qwen3-VL MoE encoder-only server crashes due to missing 'self.model' attribute
### Checklist

- [x] I searched related issues but found no solution.
- [x] The bug persists in the latest version.
- [x] Issues without environment info and a minimal reproducible demo are hard to resolve and may receive no feedback.
- [x] If this is not a bug report but a general question, please start a discussion at https://github.com/sgl-project/sglang/discussions. Otherwise, it will be closed.
- [x] Please use English. Otherwise, it will be closed.

### Describe the bug

[Version Information]	SGLang version: main branch (post-PR #19135 merge)
[Version problem]	New introduction issue (Caused by PR #19135)
[Assignee]  xujianzhao
[Issue Time]	2026-04-16
[Valid issue]	Yes
[Description]	

When launching a Qwen3-VL-MoE model in --encoder-only mode for disaggregated serving, the server crashes during weight loading with an AttributeError: 'Qwen3VLMoeForConditionalGeneration' object has no attribute 'model'. This is because the recently merged PR #19135 added a layer-skipping logic in qwen3_vl_moe.py that accesses self.model.start_layer without checking if self.model exists. In encoder-only mode, the parent class does not initialize self.model, leading to the crash.

### Reproduction

[Test Steps]	
1. Set up a multi-NPU environment (e.g., 4 NPUs). 
2. Launch an encoder server with the following arguments: sglang serve --model-path Qwen/Qwen3-VL-30B-A3B-Instruct --encoder-only --encoder-transfer-backend zmq_to_tokenizer --tp-size 2 --attention-backend ascend --disable-cuda-graph --trust-remote-code 
3. Observe the server process.

[Expected Result]	
The encoder server initializes successfully and passes the /health check.

[Actual Result]	The server process crashes during the weight loading phase with AttributeError: 'Qwen3VLMoeForConditionalGeneration' object has no attribute 'model'.

### Environment

A3, Single-node, PD Disaggregation

### PR DESCRIPTION
**Pull request by octo-patch**
Fixes #23063

## Problem

When launching a Qwen3-VL-MoE model in `--encoder-only` mode, the server crashes during weight loading with `AttributeError: 'Qwen3VLMoeForConditionalGeneration' object has no attribute 'model'`.

In encoder-only mode, `self.model` is not initialized by the parent class (`Qwen3VLForConditionalGeneration.__init__` only sets `self.model` when `config.encoder_only` is `False`). However, `Qwen3VLMoeForConditionalGeneration.load_weights` unconditionally accessed `self.model` in:

```python
and hasattr(self.model, "start_layer")
```

Python evaluates `self.model` before `hasattr` can handle the missing attribute, causing the crash.

## Solution

Add `hasattr(self, "model")` check before accessing `self.model`, matching the pattern already used in the parent class `Qwen3VLForConditionalGeneration.load_weights` in `qwen3_vl.py` (line 1322):

```python
and hasattr(self, "model")
and hasattr(self.model, "start_layer")
```

## Testing

The fix is minimal (1 line added) and directly mirrors the existing guard pattern in the parent class. Encoder-only mode now safely skips the `start_layer`/`end_layer` layer-skipping logic when no language model is initialized, while normal (non-encoder-only) mode is unaffected.

### CODE REVIEW

**Comment by hnyls2002** [comment]
Hi @octo-patch, the guard this PR adds (hasattr(self, "model") before accessing self.model.start_layer) is already present on main at python/sglang/srt/models/qwen3_vl_moe.py:238 - the same fix landed via another change. Closing as no longer needed; please reopen if there's a residual case we're missing.
