### ISSUE TITLE
[Bug] W4AFP8 + DeepEP crashes at first inference: TypeError "missing 1 required positional argument: 'routed_scaling_factor'"

### ISSUE THREAD

**Issue by thangquang09** [sgl-project/sglang#33660]
### Describe the bug

When serving a W4AFP8-quantized DeepSeek-V2 architecture model (GLM-5.2) with `--quantization w4afp8 --moe-a2a-backend deepep` (normal mode), the server boots, loads weights, and completes DeepGEMM JIT pre-compilation successfully, then **every DP/TP/EP rank crashes simultaneously on the first inference request** with:

```
TypeError: dynamic_func() missing 1 required positional argument: 'routed_scaling_factor'
```

The failure is in the W4AFP8 + DeepEP-normal MoE combine path. This is a regression introduced by #23754.

### Reproduction

Image: `lmsysorg/sglang:v0.5.16-cu130` (also reproducible on current `main`).
Hardware: 8× H200 (single node). Model: `PhalaCloud/GLM-5.2-W4AFP8` (served as `zai-org/GLM-5.2-FP8`).

Minimal command (EAGLE/MTP and hicache from the original run are **not** required to trigger the bug — the target model's MoE hits it on its own):

```bash
python3 -m sglang.launch_server \
  --model-path PhalaCloud/GLM-5.2-W4AFP8 \
  --quantization w4afp8 \
  --tp 8 --dp 4 --ep 8 \
  --enable-dp-attention --enable-dp-attention-local-control-broadcast \
  --moe-a2a-backend deepep \
  --served-model-name zai-org/GLM-5.2-FP8 \
  --host 0.0.0.0 --port 8889
```

Then send any single completion request. The crash fires immediately (no output produced).

Full original launch command (with EAGLE MTP + hicache, from the benchmark run that surfaced this):

```bash
python3 -m sglang.launch_server \
  --model-path /models/PhalaCloud/GLM-5.2-W4AFP8 --quantization w4afp8 \
  --host 0.0.0.0 --port 8889 --tp 8 --dp 4 --ep 8 \
  --enable-dp-attention --enable-dp-attention-local-control-broadcast \
  --tokenizer-worker-num 8 --dist-init-addr 127.0.0.1:10888 \
  --numa-node 0 0 0 0 1 1 1 1 \
  --moe-a2a-backend deepep --chunked-prefill-size 32768 \
  --tool-call-parser glm47 --reasoning-parser glm45 \
  --mem-fraction-static 0.75 --max-running-requests 48 --context-length 500000 \
  --kv-cache-dtype fp8_e4m3 --allow-auto-truncate --enable-metrics \
  --enable-cache-report --enable-hierarchical-cache --hicache-size 128 \
  --speculative-algorithm EAGLE --speculative-num-steps 3 \
  --speculative-eagle-topk 1 --speculative-num-draft-tokens 4 \
  --schedule-policy dfs-weight --served-model-name zai-org/GLM-5.2-FP8
```

### Expected behavior

Server serves requests. `routed_scaling_factor` from the model config (2.5 for GLM-5.2 / DeepSeek-V3.x) should be folded into the topk weights inside `deepep_post_reorder_triton_kernel`.

### Actual behavior

All 8 ranks crash at the same timestamp on first inference (server boot was ~10 min earlier; DeepGEMM JIT pre-compile completed normally). One representative traceback (dp1/tp2/ep2); the other 7 ranks fail identically:

<details><summary>Full traceback (click to expand)</summary>

```
[2026-08-04 14:43:00 DP1 TP2 EP2] Scheduler hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 4639, in run_scheduler_process
    scheduler.run_event_loop()
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1500, in run_event_loop
    dispatch_event_loop(self)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 4490, in dispatch_event_loop
    scheduler.event_loop_overlap()
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1601, in event_loop_overlap
    batch_result = self.run_batch(batch)
  File "/sgl-workspace/sglang/python/sglang/srt/utils/nvtx_utils.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 3351, in run_batch
    batch_result = self.model_worker.forward_batch_generation(
  File "/sgl-workspace/sglang/python/sglang/srt/speculative/eagle_worker_v2.py", line 1130, in forward_batch_generation
    batch_output = self.target_worker.forward_batch_generation(
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 564, in forward_batch_generation
    out = self.model_runner.forward(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1277, in forward
    output = self._forward_raw(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1463, in _forward_raw
    ret = self.eager_runner.execute(
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/runner/eager_runner.py", line 203, in execute
    return self._execute_extend(forward_batch, pp_proxy_tensors)
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/runner/eager_runner.py", line 332, in _execute_extend
    ret = model_runner.model.forward(
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 2871, in forward
    hidden_states = self.model(
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 2603, in forward
    hidden_states, residual, topk_indices = layer(
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 2275, in forward
    hidden_states = self.mlp(
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 919, in forward
    return self.forward_deepep(
  File "/sgl-workspace/sglang/python/sglang/srt/models/deepseek_v2.py", line 1399, in forward_deepep
    final_hidden_states = self.experts(
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/moe/ep_moe/layer.py", line 175, in forward
    return self.forward_impl(hidden_states, topk_output)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/moe/ep_moe/layer.py", line 192, in forward_impl
    combine_input = self.run_moe_core(dispatch_output)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/moe/ep_moe/layer.py", line 221, in run_moe_core
    output = self.forward_cutlass_w4afp8(dispatch_output)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/moe/ep_moe/layer.py", line 262, in forward_cutlass_w4afp8
    return self.quant_method.apply_deepep_normal(
  File "/sgl-workspace/sglang/python/sglang/srt/layers/quantization/w4afp8.py", line 384, in apply_deepep_normal
    return cutlass_w4a8_moe_deepep_normal(
  File "/sgl-workspace/sglang/python/sglang/srt/layers/moe/cutlass_w4a8_moe.py", line 420, in cutlass_w4a8_moe_deepep_normal
    deepep_post_reorder_triton_kernel[(num_tokens,)](
  File "/usr/local/lib/python3.12/dist-packages/triton/runtime/jit.py", line 370, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/triton/runtime/jit.py", line 710, in run
    bound_args, specialization, options = binder(*args, **kwargs)
TypeError: dynamic_func() missing 1 required positional argument: 'routed_scaling_factor'
```

</details>

### Environment

- **SGLang**: `lmsysorg/sglang:v0.5.16-cu130` (release); also confirmed on current `main`.
- **Model**: `PhalaCloud/GLM-5.2-W4AFP8` (DeepSeek-V2 arch, 256 routed experts, `routed_scaling_factor=2.5`), served as `zai-org/GLM-5.2-FP8`.
- **Quantization**: `w4afp8`, MoE runner auto-resolved to `cutlass`.
- **Parallelism**: TP=8, DP=4, EP=8, `--enable-dp-attention`, `--moe-a2a-backend deepep` (`deepep_mode=auto` → normal for prefill).
- **Hardware**: 8× NVIDIA H200 (single node).
- **Speculative**: EAGLE MTP, draft also w4afp8 (not required to repro).

**Comment by thangquang09** [comment]
## Additional finding: W4AFP8 + DeepEP also fails with Unsupported type at intranode.cu:926

@CyberSecurityErial I tested your PR #33669 fix (passing routed_scaling_factor=1.0 to deepep_post_reorder_triton_kernel) — that TypeError is correctly fixed. But on Hopper (4xH200, single node, TP4 EP4, --deepep-mode auto) the server now boots, completes DeepGEMM JIT warmup, processes 2 prefill batches, and then all ranks crash on the second prefill with:

RuntimeError: Failed: Assertion error /build/DeepEP/csrc/kernels/intranode.cu:926 'false and Unsupported type'

This is a separate, deeper issue: DeepEP's intranode a2a kernel does not support the W4AFP8 weight dtype (INT4 weights, FP8 activations). It rejects 'Unsupported type' at the dispatch site.

### Reproduction
- Image: lmsysorg/sglang:v0.5.16-cu130 + your #33669 patch applied
- Model: PhalaCloud/GLM-5.2-W4AFP8 (--quantization w4afp8)
- Parallelism: --tp 4 --ep 4 --moe-a2a-backend deepep --deepep-mode auto
- Hardware: 4xH200 (single node)
- The first prefill (seq=1, 64 tokens) succeeds; the second (seq=3, 192 tokens) triggers the crash

### What works
Dropping DeepEP (--moe-a2a-backend none) boots fine — the built-in NCCL TP-MoE path handles W4AFP8. The routed_scaling_factor=1.0 fix in #33669 is still correct and needed for the DeepEP-normal path when it eventually supports W4AFP8, but on Hopper today W4AFP8 + DeepEP cannot run.

This may be Hopper-specific (the prod 8xH200 config also uses W4AFP8 + DeepEP and hits #33660 first). Linking here so the DeepEP INT4-weight support gap is tracked alongside the routed_scaling_factor fix.

**Comment by CyberSecurityErial** [comment]
Thanks for validating the first fix. I traced the pinned DeepEP source: `intranode.cu:926` is the normal **combine** BF16-only dtype switch, not an INT4-weight dispatch site; W4 weights never enter DeepEP.

The actual issue is mode-dependent activation format. W4AFP8 normal/prefill needs BF16 because it requantizes with checkpoint static scales, while low-latency/decode needs FP8 plus its per-token-group scales. Previously `auto` selected FP8 for both; normal discarded the scale, and a zero-token rank returned FP8 into DeepEP combine, causing the assertion. A global BF16 override would therefore break decode.

I updated #33669 to use normal=`bf16` and low-latency=`fp8`, added guards and CPU regressions, and rebased it onto current `main`. Could you please retest the updated branch on your 4xH200 setup?

**Comment by thangquang09** [comment]
@CyberSecurityErial Retested the updated #33669 on 4×H200 (single node) — **both issues are fixed.**

**Setup:** `lmsysorg/sglang:v0.5.16-cu130` + your updated branch, `--quantization w4afp8 --tp 4 --ep 4 --moe-a2a-backend deepep --deepep-mode auto`.

- The `routed_scaling_factor` `TypeError` no longer fires.
- The `intranode.cu:926 'Unsupported type'` crash on the 2nd prefill is gone — your mode-specific dispatcher dtype fix (normal=bf16, low-latency=fp8) resolves it. Multi-seq prefill (seq=3, 192 tokens, and larger batches) now runs cleanly and repeatedly; previously it crashed on the second prefill.
- Decode low-latency path (fp8 dispatcher) works under cuda graph; output is coherent; the 5 added CPU regressions pass; 0 errors in the server log.

I also A/B'd `deepep` vs `none` (NCCL TP-MoE) under load on the same box — TP4 EP4 DP4 dp-attention, 8k/1k random, seed 0, `num-prompts=CONC*10`, `max-running-requests=2*CONC`, `cuda-graph-max-bs=64`:

| conc | a2a backend | output tok/s | total tok/s | mean TTFT (ms) | mean TPOT (ms) |
|------|-------------|--------------|-------------|----------------|----------------|
| 16 | deepep | 415 | 3739 | 6297 | 32.4 |
| 16 | none   | 421 | 3788 | 5626 | 32.6 |
| 32 | deepep | 609 | 5481 | 10715 | 42.1 |
| 32 | none   | 614 | 5526 | 9558 | 42.8 |

On single-node NVLink, NCCL TP-MoE remains marginally ahead; deepep's value is on multi-node / inter-node EP where NCCL allreduce is the bottleneck. The fix itself is solid: W4AFP8 + DeepEP now runs correctly end-to-end.

LGTM, thanks!
