### PR TITLE
[Feature] Support BF16 and batch-invariant inference with DeepEP v2

### PR DESCRIPTION
**Pull request by ch-wan**
## Summary

Enable BF16 checkpoints and batch-invariant inference with `--moe-a2a-backend deepep_v2`, and fix a missing-argument error in the existing FP8 prefill path.

The wire dtype follows the expert weights: BF16 experts receive BF16 activations; supported blockwise FP8 experts receive FP8 activations and scales. With `--enable-deterministic-inference`, tokens retain identical results when changes in batch size move them between TP ranks. Decode CUDA graphs remain enabled.

### Fix contiguous scatter

#35758 added `expert_start` and `num_experts` to `_fwd_kernel_ep_scatter_2` without updating the DeepEP v2 `ep_scatter_from_psum` caller introduced in #35634. Prefill raises:

```text
TypeError: dynamic_func() missing 2 required positional arguments:
'expert_start' and 'num_experts'
```

Pass `expert_start=0` and the local expert count because DeepEP v2 already rebases received expert IDs. Add CUDA tests for BF16 and FP8 inputs; both fail on the PR base and pass with the fix.

### Support BF16 communication

- Resolve the dispatch dtype from the expert quantization method and reject a conflicting `--deepep-dispatcher-output-dtype`. Require the quantization method when creating the dispatcher so an omitted argument cannot silently select FP8.
- Pass `use_fp8_dispatch` to `ElasticBuffer`, skipping activation quantization for BF16 experts in both prefill and decode.
- Accept scale-free BF16 dispatch output in the DeepGEMM adapter and avoid allocating activation scales for it.
- Admit unquantized BF16 experts while preserving the existing blockwise FP8 contract and DeepGEMM runner requirement.

### Enable batch-invariant inference

The remaining batch dependence was in TP reduce-scatter **before the MoE**. Its floating-point summation order depends on the receiving rank. As a serving batch grows, a token can move to another rank and enter the first MoE layer with different bits.

Under deterministic inference, `GroupCoordinator.reduce_scatter_tensor` now uses the existing deterministic all-reduce path followed by a local slice. It clones the input to preserve the input contract, including callers whose output aliases an input slice. Other modes retain native reduce-scatter.

Remove the DeepEP v2 deterministic-inference rejection. Leave ElasticBuffer receive sorting disabled: expert computation is row-independent and combine follows the handle's slot pointers; the sort's dynamic indexing is also incompatible with decode CUDA graph capture.

## Validation

Fresh validation on **4×B200**, TP4/EP4, DeepEP 2.1.0, Torch 2.13.0+cu130, NCCL 2.30.7, direct mode and Triton attention. Radix caching was disabled so every request recomputed prefill; DeepGEMM precompilation remained enabled.

| Check | Result |
|---|---|
| BF16/FP8 dtype, runner, buffer lifecycle and masked-slab unit tests | 49 passed, plus 2 subtests |
| BF16/FP8 contiguous scatter CUDA tests | 2 passed; both fail on the PR base |
| Distributed and server-argument unit tests | 215 passed, plus 20 subtests |
| New four-GPU collective regression | 6 cases passed at the production default of 8 NCCL channels: BF16/FP16/FP32, eager and CUDA graphs |
| Qwen3-30B-A3B, BF16 and FP8: three prompts, every batch size 1–20 | All 32 output-token IDs and logprobs exactly match, including every duplicate within each batch |
| Both checkpoints: unrelated variable-length prompts, target request last, batch sizes through 32 | Exact output-token IDs and logprobs |
| Both checkpoints: 1,350-token prompt, batch sizes 1/2/3/4/8, crossing the 4,096-token prefill chunk budget | Exact results for 32 generated tokens |
| Pre-commit checks | Passed |

Decode CUDA graphs were captured at batch sizes 4, 8, 12, 16, 24 and 32 and used during the model checks. Prefill retains the existing eager execution policy.

The collective regression fails on the unpatched PR head: identical token contributions produce different results across destination ranks in 2,550 of 8,192 BF16 elements (31.1%). All-rank model instrumentation likewise showed migrating tokens differing at the first layer's MoE input before the fix and matching afterward.

The combined wire-dtype, scatter, runner, distributed and server-argument test suite passed **244 tests plus 22 subtests**. The collective regression uses `SGLANG_DETERMINISTIC_NCCL_NCHANNELS` to follow production configuration.

The PR includes a model-free four-GPU CI regression and a manual exact-logprob probe, `test/manual/ep/test_deepep_v2_deterministic.py`, with a server launch example. The manual probe verifies that deterministic inference is enabled and radix caching is disabled.

### Earlier accuracy measurements

Previously recorded on 4×B300, TP4/EP4/DP4-attention, direct mode, GSM8K 300 examples:

| Model | A2A backend | GSM8K |
|---|---|---:|
| Qwen3-30B-A3B | `deepep_v2`, BF16 | 96.33% |
| Qwen3-30B-A3B | `none` | 96.00% |
| Qwen3-30B-A3B-FP8 | `deepep_v2`, FP8 | 95.00% |

These accuracy measurements predate the deterministic reduce-scatter fix and were not rerun for that commit.

## Costs and scope

- BF16 dispatch carries approximately twice the activation payload of FP8; total ElasticBuffer allocation does not necessarily double.
- Deterministic reduce-scatter now requires all-reduce communication and a full-input temporary. End-to-end performance overhead has not been benchmarked.
- Fresh model validation covers the two homogeneous BF16/FP8 Qwen3 checkpoints above on one node in direct mode. Multi-node/hybrid transport and other model families were not exercised.
- Alternating BF16/FP8 MoE layers change the singleton ElasticBuffer cache key and can trigger collective buffer rebuilds at layer transitions; mixed-quantization checkpoints need separate lifecycle coverage.

## Checklist

- [x] Format code with pre-commit.
- [x] Add unit and GPU regression tests.
- [x] Include a reproducible manual batch-invariance test and launch command.
- [x] Report accuracy and exact-logprob validation results, with their scope.
- [ ] Benchmark deterministic-mode performance overhead.
- [ ] Update the user documentation.

---
### CI States

Latest PR Test (Base): :white_check_mark: [Run #34944654646](https://github.com/sgl-project/sglang/actions/runs/34944654646)
Latest PR Test (Extra): :x: [Run #34944654351](https://github.com/sgl-project/sglang/actions/runs/34944654351)
Latest PR Test (AMD ROCm 10): :x: [Run #34944654505](https://github.com/sgl-project/sglang/actions/runs/34944654505)

### CODE REVIEW

File: test/registered/kernels/ops/communication/test_deterministic_reduce_scatter.py [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+@pytest.fixture(scope="module")
+def group():
+    rank = int(os.environ["RANK"])
+    world_size = int(os.environ["WORLD_SIZE"])
+    local_rank = int(os.environ["LOCAL_RANK"])
+    # Match --enable-deterministic-inference's CUDA collective settings.
+    os.environ["SGLANG_ENABLE_DETERMINISTIC_INFERENCE"] = "1"
+    os.environ["NCCL_ALGO"] = "allreduce:tree"
+    os.environ["NCCL_MIN_NCHANNELS"] = "1"
+    os.environ["NCCL_MAX_NCHANNELS"] = "1"
```
Comment (ch-wan) [inline test/registered/kernels/ops/communication/test_deterministic_reduce_scatter.py]: The comment above says these match `--enable-deterministic-inference`, but production pins the channel count from `SGLANG_DETERMINISTIC_NCCL_NCHANNELS`, whose default is **8** (`environ.py:1267`), not 1.

Tree shape and therefore the reduction order depend on the channel count, so as written this test validates a configuration production never runs, and a regression that only appears at 8 channels would pass here.

```suggestion
    os.environ["NCCL_MIN_NCHANNELS"] = str(envs.SGLANG_DETERMINISTIC_NCCL_NCHANNELS.get())
    os.environ["NCCL_MAX_NCHANNELS"] = str(envs.SGLANG_DETERMINISTIC_NCCL_NCHANNELS.get())
```
(needs `from sglang.srt.environ import envs`.)

File: python/sglang/srt/distributed/parallel_state.py [hunk 2]
```diff
@@ -1087,7 +1087,19 @@ def _reduce_scatter_tensor(
...
 
     def reduce_scatter_tensor(self, output: torch.Tensor, input: torch.Tensor):
-        if _is_npu or _is_cpu:
+        if envs.SGLANG_ENABLE_DETERMINISTIC_INFERENCE.get():
+            assert input.numel() == output.numel() * self.world_size
+            # A reduce-scatter ring sums in a different order for each receiving
+            # rank. A token can move between ranks as the batch size changes,
+            # so use the deterministic all-reduce path before selecting its shard.
+            # Clone because callers may retain input or alias output into it.
+            reduced = self.all_reduce(input.clone())
```
Comment (ch-wan) [inline python/sglang/srt/distributed/parallel_state.py]: Worth stating the cost here, since it is paid per reduce-scatter call, per layer, per forward:

- an all-reduce moves `2(N-1)/N` of the payload against reduce-scatter's `(N-1)/N`, so this roughly **doubles the collective traffic**;
- `input.clone()` adds a **full-size** (unsharded) allocation each call.

Not arguing against the trade -- deterministic mode already gives up a lot, and correctness wins -- but neither the comment nor the PR body mentions it, and someone profiling deterministic mode will find this and wonder. One line like "costs ~2x the collective traffic of a reduce-scatter" would save that.

File: test/registered/unit/layers/moe/test_deepep_v2_contig_scatter.py [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+register_cuda_ci(est_time=10, stage="base-b", runner_config="1-gpu-small")
+
+DEVICE = "cuda"
+HIDDEN = 256
+SCALE_HIDDEN = HIDDEN // 128
+# Match the scatter kernel's BLOCK_E alignment.
+ALIGN = 128
+
+
+class TestDeepEPv2ContigScatter(CustomTestCase):
```
Comment (ch-wan) [inline test/registered/unit/layers/moe/test_deepep_v2_contig_scatter.py]: The cleanup commit dropped this class's docstring, which stated what the test guards.

`.claude/rules/comment-style.md` lists a bug-regression test docstring as one of the surfaces that **keeps** documentation: *"a bug-regression test, stating in one or two lines which black-box behavior must not come back -- the live constraint, not the incident."*

Dropping the `TypeError` / PR-#35758 narration is right by that rule (incident detail belongs in the PR), but the first line was the sanctioned part. Suggest keeping just the constraint:

```suggestion
class TestDeepEPv2ContigScatter(CustomTestCase):
    """Guards `ep_scatter_from_psum`, the DeepEP v2 prefill permute."""

```

File: python/sglang/srt/layers/moe/fused_moe_triton/layer.py [hunk 4]
```diff
@@ -157,7 +159,10 @@ def _get_deepep_comm_group(a2a_backend):
     return group
 
 
-def create_moe_dispatcher(moe_runner_config: MoeRunnerConfig) -> BaseDispatcher:
+def create_moe_dispatcher(
+    moe_runner_config: MoeRunnerConfig,
+    quant_method: Optional[FusedMoEMethodBase] = None,
```
Comment (ch-wan) [inline python/sglang/srt/layers/moe/fused_moe_triton/layer.py]: `quant_method=None` silently resolves to the FP8 wire: `_deepep_v2_experts_are_fp8(None)` returns `not isinstance(None, UnquantizedFusedMoEMethod)` == `True`.

There is exactly one production caller and it passes the kwarg, so nothing is broken today. But the default means "forgot to pass it" lands on an FP8 wire for a BF16 checkpoint rather than failing, and `use_fp8_dispatch` is part of the `DeepEPv2Buffer` cache key, so the mistake would surface as a mis-sized buffer rather than an error.

Since there is one caller, making it required costs nothing:

```suggestion
    quant_method: FusedMoEMethodBase,
```

File: python/sglang/srt/layers/moe/token_dispatcher/deepep_v2.py [hunk 5]
```diff
@@ -427,6 +432,7 @@ def __init__(
         num_local_experts: int,
         hidden_size: int,
         params_dtype: torch.dtype,
+        use_fp8_dispatch: bool = True,
```
Comment (ch-wan) [inline python/sglang/srt/layers/moe/token_dispatcher/deepep_v2.py]: **[suggestion]** `DeepEPv2Dispatcher.__init__` still defaults `use_fp8_dispatch: bool = True`. The factory now requires `quant_method` so an omitted argument cannot silently pick FP8, but any direct constructor (tests, future callers, `_DeepEPv2Impl` built by hand) still sizes ElasticBuffer for an FP8 wire and will quantize BF16 experts. DeepEP's own `ElasticBuffer` default is `use_fp8_dispatch=False`.

**Suggestion:** Drop the default and require `use_fp8_dispatch` at both `DeepEPv2Dispatcher` and `_DeepEPv2Impl`, matching the required `quant_method` on `create_moe_dispatcher`.

File: python/sglang/srt/distributed/parallel_state.py [hunk 6]
```diff
@@ -1087,7 +1087,17 @@ def _reduce_scatter_tensor(
         return output
 
     def reduce_scatter_tensor(self, output: torch.Tensor, input: torch.Tensor):
-        if _is_npu or _is_cpu:
+        if envs.SGLANG_ENABLE_DETERMINISTIC_INFERENCE.get():
+            assert input.numel() == output.numel() * self.world_size
+            # Reduction order must be independent of the receiving rank.
+            # Preserve input even when all_reduce mutates its argument.
+            reduced = self.all_reduce(input.clone())
```
Comment (ch-wan) [inline python/sglang/srt/distributed/parallel_state.py]: **[suggestion]** The deterministic path clones the full reduce-scatter input on every call so in-place all-reduce and aliased outputs stay safe. That is correct, but decode CUDA graphs will capture a per-layer temporary the size of the gathered activation, and eager prefill doubles the live activation footprint for the duration of the collective. `reduce_scatterv` is unchanged, so the opt-in DP gatherv path (`SGLANG_DP_USE_GATHERV`) still uses native rank-dependent reduce-scatter.

**Suggestion:** If this stays on the hot path, prefer a graph-static workspace over `input.clone()`, and either document that gatherv is outside the determinism guarantee or apply the same all-reduce-then-slice treatment when `sizes` are equal.
