### PR TITLE
[AMD] [Not-Merge] Move getSMVersion to runtime.cuh and fix ROCm compile (dedup with get_cc_major)

### PR DESCRIPTION
**Pull request by kangwangamd**
## Motivation

`getSMVersion()` (added by #30438, "Delete CUTLASS FP8 blockwise… move SM120 to JIT + SwapAB") lives in `python/sglang/jit_kernel/include/sgl_kernel/utils.cuh` and calls:

```cpp
cudaDeviceGetAttribute(&sm_major, cudaDevAttrComputeCapabilityMajor, device_id);
cudaDeviceGetAttribute(&sm_minor, cudaDevAttrComputeCapabilityMinor, device_id);
```

`cudaDevAttrComputeCapabilityMajor/Minor` are **CUDA-only** enums (SM / compute-capability is an NVIDIA concept) and do not exist under HIP. Because `utils.cuh` is an inline header included transitively by **nearly every JIT translation unit**, this fails to compile in every gfx950 (MI355X) JIT TU:

```
error: use of undeclared identifier 'cudaDevAttrComputeCapabilityMajor'
error: use of undeclared identifier 'cudaDevAttrComputeCapabilityMinor'
2 errors generated when compiling for gfx950.
```

This breaks JIT compilation of **all DeepSeek-V4 kernels on gfx950**, turning 8/9 MI355X-disaggregation benchmarks red (regression since #30438 landed; last-passing `4cec9ef9d`, first-failing merge `7431f35fd`).

## Modifications

Guard `getSMVersion()` with `#ifndef USE_ROCM`, matching the other CUDA-only blocks already guarded in this same file. `getSMVersion` has **no ROCm-JIT caller** — its only reference in the JIT tree is its own definition, and the SM120 arch-gating is done in Python (`fp8_blockwise_gemm.py` → `is_sm120_supported()`), so guarding the whole function out on ROCm is safe. **No CUDA-path change.**

## Validation

Compile-verified with `hipcc -DUSE_ROCM` (compile-only; no GPU needed since this is a compile-time break):

| arch | stock (unguarded) | this PR (guarded) |
|---|---|---|
| **gfx950 (MI355X)** — the failing arch, HIP 7.2 | ❌ `undeclared identifier cudaDevAttrComputeCapability*` → "2 errors compiling for gfx950" | ✅ compiles clean (exit 0) |
| gfx942 (MI300X), HIP 7.2 | ❌ same errors | ✅ compiles clean (exit 0) |

cc @b8zhong (author of #30438) @BBuf — please take a look. Also cc @AMD-yanfeiwang @kkHuang-amd for ROCm review.

---
### CI States

Latest PR Test (Base): :white_check_mark: [Run #29559518750](https://github.com/sgl-project/sglang/actions/runs/29559518750)
Latest PR Test (Extra): :x: [Run #29559518679](https://github.com/sgl-project/sglang/actions/runs/29559518679)

### CODE REVIEW

**Comment by DarkSharpness** [comment]
Actually `getSMVersion` should be moved out of `utils.cuh` into `runtime.cuh` (it's a CUDA runtime call) (you may need to change the use-site) https://github.com/sgl-project/sglang/blob/440aebdfe0f650bf61f9fb5c7a6570c37e2effea/python/sglang/jit_kernel/include/sgl_kernel/runtime.cuh#L1-L86 and deduplicate with `get_cc_major`. Could you please help fix that? Also, the guard might not be needed after #31141

**Comment by kangwangamd** [comment]
Thanks @DarkSharpness, that's a much cleaner approach — `runtime.cuh` already has the `cuda*→hip*` attribute shims (so no `#ifndef USE_ROCM` guard is needed there) plus `get_cc_major`. I'll:

1. Move `getSMVersion` from `utils.cuh` into `runtime.cuh` (dropping the guard).
2. Deduplicate against `get_cc_major` — add a matching `get_cc_minor` (and the `cudaDevAttrComputeCapabilityMinor → hipDeviceAttributeComputeCapabilityMinor` `#define`, which isn't there yet) and express `getSMVersion` as `get_cc_major(id) * 10 + get_cc_minor(id)`.
3. Note: in the JIT tree `getSMVersion` currently has no caller (its only reference was its own definition — the direct call was removed in #30438), so no use-site change is needed here; I'll double-check after the move.

Will push shortly and re-verify the gfx950 compile.

**Comment by kangwangamd** [comment]
@DarkSharpness done — pushed the rework:
- Removed the guarded `getSMVersion` from `utils.cuh`.
- Moved it into `runtime.cuh`, added the `cudaDevAttrComputeCapabilityMinor → hipDeviceAttributeComputeCapabilityMinor` `#define` + a `get_cc_minor`, and defined `getSMVersion(id) = get_cc_major(id) * 10 + get_cc_minor(id)` to dedup the attribute queries.
- No `#ifndef USE_ROCM` guard needed — the shims in `runtime.cuh` make it compile on both platforms. No JIT-tree caller, so no use-site change.

Compile-verified on gfx950 (MI355X, `hipcc -DUSE_ROCM --offload-arch=gfx950`): the moved function now compiles clean via the HIP attribute shims (present, not guarded out). PTAL 🙏

File: python/sglang/jit_kernel/include/sgl_kernel/runtime.cuh [hunk 1]
```diff
@@ -68,6 +71,18 @@ inline auto get_cc_major(int device_id) -> int {
...
 
+// Return the Minor compute capability for the given device
+inline auto get_cc_minor(int device_id) -> int {
+  int cc_minor;
+  RuntimeDeviceCheck(cudaDeviceGetAttribute(&cc_minor, cudaDevAttrComputeCapabilityMinor, device_id));
+  return cc_minor;
+}
+
+// Return the SM version (major * 10 + minor) for the given device
+inline auto getSMVersion(int device_id) -> int {
```
Comment (DarkSharpness) [inline python/sglang/jit_kernel/include/sgl_kernel/runtime.cuh]: I'd prefer `get_sm_version`.

**Review by DarkSharpness — APPROVED** [review]
Thanks. LGTM

**Comment by kangwangamd** [comment]
Done — renamed to `get_sm_version` for snake_case consistency (`6a09fb0`). Thanks for the review!

**Comment by kangwangamd** [comment]
Closing this out — it was always marked `[Not-Merge]` (a proposal/discussion PR), and the ROCm fix it described is now on `main`: `runtime.cuh` already provides the HIP mappings for `cudaDevAttrComputeCapabilityMajor/Minor` (via `hipDeviceAttributeComputeCapability*`), so `get_sm_version` compiles under hipcc without the guard this PR proposed. This branch's diff is now empty (0 files) against main. Thanks @DarkSharpness for the `runtime.cuh` direction — that's where it landed. Closing as obsolete/superseded.
