### PR TITLE
Fix canonical YAML options shadowed by deprecated aliases

### PR DESCRIPTION
**Pull request by gaoxiaomo**
## Summary

- decide YAML support using every argparse action registered for a destination;
- keep canonical `_StoreAction` and `_StoreTrueAction` options available when a deprecated alias shares the same `dest`;
- continue rejecting destinations that only have unsupported custom actions;
- add focused coverage for canonical value options, canonical boolean options, and custom-only actions.

## Problem

`ConfigArgumentMerger` currently builds `unsupported_actions` one action at a
time. A deprecated alias is a custom argparse action and can share its
destination with a supported canonical option. When that happens, the alias
marks the whole destination as unsupported, so a valid YAML option such as
`cuda-graph-max-bs-decode: 8` raises `Unsupported config option`.

Support belongs to the complete action set for a destination, not whichever
custom action happens to be registered last. This change first collects the
destinations backed by a standard store action, then excludes those
destinations from `unsupported_actions`.

The deprecated CLI alias still parses and emits its warning. The change does
not expose the deprecated alias as a new YAML key.

This addresses the YAML parsing regression reported in #29184. It is a narrow
parser fix and does not implement the broader device-graph naming RFC.

## Tests

- focused regression tests: 3/3 passed;
- real `ServerArgs` check: canonical YAML resolved to `8`; deprecated CLI alias
  resolved to `9` and retained its deprecation warning;
- isort, Ruff, Black, codespell, registered-test validation, bare-pytest-main
  validation, `py_compile`, and `git diff --check` passed.

---
### CI States

Latest PR Test (Base): :x: [Run #32832362694](https://github.com/sgl-project/sglang/actions/runs/32832362694)
Latest PR Test (Extra): :x: [Run #32832362611](https://github.com/sgl-project/sglang/actions/runs/32832362611)
Latest PR Test (AMD ROCm 7.2): :x: [Run #32832362656](https://github.com/sgl-project/sglang/actions/runs/32832362656)

### CODE REVIEW

**Comment by gaoxiaomo** [comment]
The previous red `pr-gate` checks were caused by the missing `run-ci` label; the lint workflow passed, and the downstream test jobs were skipped rather than failing in the code.

I have rebased the branch on current `main` (`3bc1c580c`). The focused regression tests and local validation are listed in the PR description. Could a maintainer please review the scope and add the `run-ci` label when appropriate?
