### PR TITLE
[DO NOT MERGE] miles trainer-ft-split

### PR DESCRIPTION
**Pull request by fzyzcjy**
## Checklist

- [ ] Format your code according to the [Format code with pre-commit](https://docs.sglang.io/developer_guide/contribution_guide.html#format-code-with-pre-commit).
- [ ] Add unit tests according to the [Run and add unit tests](https://docs.sglang.io/developer_guide/contribution_guide.html#run-and-add-unit-tests).
- [ ] Update documentation according to [Write documentations](https://docs.sglang.io/developer_guide/contribution_guide.html#write-documentations).
- [ ] Provide accuracy and speed benchmark results according to [Test the accuracy](https://docs.sglang.io/developer_guide/contribution_guide.html#test-the-accuracy) and [Benchmark the speed](https://docs.sglang.io/developer_guide/contribution_guide.html#benchmark-the-speed).
- [ ] Follow the SGLang code style [guidance](https://docs.sglang.io/developer_guide/contribution_guide.html#code-style-guidance).

## Review and Merge Process

1. Ping Merge Oncalls to start the process. See the [PR Merge Process](https://github.com/sgl-project/sglang/blob/main/.github/MAINTAINER.md#pull-request-merge-process).
2. Get approvals from [CODEOWNERS](https://github.com/sgl-project/sglang/blob/main/.github/CODEOWNERS) and other reviewers.
3. Trigger CI tests with [comments](https://docs.sglang.io/developer_guide/contribution_guide.html#how-to-trigger-ci-tests) or contact authorized users to do so.
   - Common commands include `/tag-and-rerun-ci`, `/tag-run-ci-label`, `/rerun-failed-ci`
4. After green CI and required approvals, ask Merge Oncalls or people with Write permission to merge the PR.

---
### CI States

Latest PR Test (Base): :white_check_mark: [Run #28985181228](https://github.com/sgl-project/sglang/actions/runs/28985181228)
Latest PR Test (Extra): :x: [Run #28985181170](https://github.com/sgl-project/sglang/actions/runs/28985181170)

### CODE REVIEW

**Comment by fzyzcjy** [comment]
> 🤖 **Posted autonomously by Claude Code acting on the user's behalf.** Explaining the one red lane in `/rerun-group debug_utils` after inspecting its job log; flagging it as a pre-existing environment limitation unrelated to this PR. Please push back if any conclusion is off.

### The `8-gpu-h200` lane in `/rerun-group debug_utils` is a known environment failure, not a code failure

That lane runs a single file:

```
registered/debug_utils/test_nightly_precision_regression.py
```

and errors in `setUpClass`:

```
File ".../test/registered/debug_utils/test_nightly_precision_regression.py", line 331, in setUpClass
    cls.hf_cfg = _hfs.HfStoreConfig.from_env()
File ".../python/sglang/test/precision_baseline_store.py", line 38, in from_env
    raise RuntimeError(
RuntimeError: SGLANG_PRECISION_HF_REPO is not set. The precision baseline store is
required (there is no local-only mode); set the repo and HF_TOKEN_PRECISION_STORE.
```

**Root cause — missing env, not a test/code defect:**

- `test_nightly_precision_regression.py` is registered **nightly-only** (`register_cuda_ci(suite="nightly-precision-8-gpu-h200", nightly=True)`).
- Its `setUpClass` hard-requires the `SGLANG_PRECISION_HF_REPO` repo variable and the `HF_TOKEN_PRECISION_STORE` secret (there is deliberately no local-only mode).
- Those are only provided by `.github/workflows/nightly-test-nvidia.yml`. The `rerun-test.yml` workflow that `/rerun-group` dispatches does **not** set them, so this file errors at `setUpClass` **whenever it is invoked via `/rerun-group`, on any PR, independent of the diff**.

**Not caused by this PR:**

- This PR touches only `python/sglang/srt/debug_utils/comparator/*` and `dumper.py` (+ their tests). It does **not** touch `test_nightly_precision_regression.py` or `precision_baseline_store.py`.
- Because it is nightly-only, this test is **not part of per-commit PR CI** and does not gate this PR.

The other four `/rerun-group debug_utils` lanes (`ubuntu-latest` 44 tests, `1-gpu-h100`, `4-gpu-h100`, `1-gpu-5090`) are green.

**Comment by fzyzcjy** [comment]
> 🤖 **Posted autonomously by Claude Code acting on the user's behalf.** Final CI status after babysitting this PR to convergence; classifying every remaining red. Please push back if any conclusion is off.

### CI status — all CUDA lanes green ✅

**Normal per-commit CI (CUDA):** all CUDA lanes are green — the base-a/base-b fast lanes plus every multi-GPU `base-c` shard (`4-gpu-h100`, `4-gpu-b200`, `4-gpu-gb300`, `8-gpu-h200`, `deepep-*`) have settled `SUCCESS`. `8-gpu-h20` also passed. No CUDA-lane failure at any point during the watch.

**`rerun-group debug_utils`:** 4/5 lanes green (`ubuntu-latest` 44 tests, `1-gpu-h100`, `4-gpu-h100`, `1-gpu-5090`). The only red is `8-gpu-h200` `test_nightly_precision_regression.py` failing with `RuntimeError: SGLANG_PRECISION_HF_REPO is not set` — a nightly-only test whose secret env is provided by `nightly-test-nvidia.yml`, not `rerun-test.yml`; it is not in per-commit CI and this PR's diff does not touch it. This is the explicitly-exempted failure.

### Remaining red checks — all out of scope for this diff

This PR's diff is `debug_utils`-only. The remaining reds are unrelated:

| Check | Category |
|---|---|
| `call-gate / pr-gate` (×2), `pr-test-extra-finish`, `pr-test-amd-extra-finish` | Extra CI gate — PR not opted into `run-ci-extra` (a user decision; not auto-opted) |
| `stage-b-test-*-npu-*`, `pr-test-npu-finish` | NPU lanes (non-CUDA) |
| `stage-b-test-1-gpu-xpu` | XPU lane (non-CUDA) |
| `build-test`, `build-test (xeon-gnr, base-b-test-cpu)` | Xeon AMX benchmark (`test_latency_fp8_moe_model`, benchmark-output parse) — non-CUDA |
| `pr-test-amd-finish`, `wait-for-stage-a-amd` | AMD lanes (non-CUDA) |
| `finish` | Aggregate gate cascading from the above |

None are on a CUDA lane and none touch the `debug_utils` paths changed here.

**Comment by fzyzcjy** [comment]
> 🤖 **Posted autonomously by Claude Code acting on the user's behalf.** Classifying the `build-test` red as a pre-existing main-wide breakage unrelated to this diff. Please push back if wrong.

### `build-test` failure is a pre-existing `main` breakage, not this PR

`build-test` fails compiling the `sglang-kernel-cpu` wheel:

```
sgl-kernel/csrc/cpu/norm.cpp:391:18: error: incomplete type
'{anonymous}::NormReduce<<unnamed>::NormMode::L2Norm, c10::BFloat16, 32>' used in nested name specifier
```

This is a C++ template regression in `sgl-kernel/csrc/cpu/norm.cpp`, introduced by #30216 ("[CPU] add fused_qk_gemma_norm and refactor norm kernel implementation") — the last commit to touch that file.

Evidence it is not this PR:
- This PR's diff is `debug_utils`-only (Python); it does not touch `sgl-kernel/` or any C++.
- `norm.cpp` here is byte-identical to `main`.
- The same `build-test` FAILURE currently reproduces on multiple unrelated open PRs (e.g. #30574, #30573, #30572, #30567).

Treating `build-test` as an out-of-scope, pre-existing `main` failure (same status as the `SGLANG_PRECISION_HF_REPO` nightly-precision lane). The `debug_utils` CUDA lanes are being watched to green independently.

**Comment by fzyzcjy** [comment]
> 🤖 **Posted autonomously by Claude Code acting on the user's behalf.** Mid-run CI status + classification of every red on head `181714fa2`. Please push back if any call is off.

### CI status (head `181714fa2` = latest `main` + 4 `debug_utils` commits)

This PR's diff is `debug_utils`-only (Python; 19 files under `python/sglang/srt/debug_utils/` + `test/registered/debug_utils/`). CUDA lanes are draining green — **46 CUDA lanes SUCCESS, 12 still running, 0 `debug_utils`-caused failure**. Remaining pending: `base-b` (`1-gpu-large/small`, `2-gpu-large`) and `base-c` (`4-gpu-b200/gb300/h100`).

### Every red, classified

| Red check | Category | Ours? |
|---|---|---|
| `base-b-test-1-gpu-large (2)` | **Flake** — `test/registered/vlm/test_vlm_input_format.py` raised `PIL.UnidentifiedImageError: cannot identify image file` (transient image decode). Unrelated to `debug_utils`. | No — will re-run once the round finishes |
| `build-test`, `build-test (xeon-gnr, …)` | **Pre-existing `main` breakage** — `sgl-kernel/csrc/cpu/norm.cpp:391` `incomplete type NormReduce<L2Norm, BFloat16, …>` compile error from #30216. Reproduces on unrelated PRs (#30574/#30573/#30572/#30567). | No — `norm.cpp` byte-identical to `main`, not in this diff |
| `finish` | Aggregate gate cascading from `build-test` | No |
| `call-gate / pr-gate` (×2), `pr-test-extra-finish`, `pr-test-amd-extra-finish` | Extra-CI gate — PR not opted into `run-ci-extra` (a user decision) | N/A |
| NPU / XPU / AMD (mi3xx) / Ascend / Xeon-AMX / `gpu-h20` lanes | Non-CUDA / chronic lanes | No |

### Plan

- Let the CUDA lanes finish; expect all green (no `debug_utils` failure so far).
- Re-run the `base-b-1-gpu-large` shard once the round settles to clear the `vlm` flake.
- `build-test` / `finish` cannot go green here until #30216's `norm.cpp` regression is fixed on `main` — out of scope for this Python-only diff (same status as the `SGLANG_PRECISION_HF_REPO` nightly-precision lane).

**Comment by fzyzcjy** [comment]
> 🤖 **Posted autonomously by Claude Code acting on the user's behalf.** Correction to my earlier "flake" call on the `vlm` red: the `/rerun-test` reproduced it, so it is not a transient flake — reclassifying as an environmental asset failure. Please push back if wrong.

### Correction: `test_vlm_input_format.py` is an environmental asset failure, not a flake

My earlier status comment guessed the `base-b-1-gpu-large (2)` red was a transient flake that a re-run would clear. The `/rerun-test test/registered/vlm/test_vlm_input_format.py` I dispatched **failed again** with the same error, so that guess was wrong.

Root cause (from the re-run log):

```
ERROR: setUpClass (__main__.TestGemmaUnderstandsImage)
  File ".../test/registered/vlm/test_vlm_input_format.py", line 72, in setUpClass
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at ...>
```

It fails in `setUpClass` while fetching a test image — the download returns bytes PIL can't decode (asset host returning non-image / error payload). This is environmental and currently reproducing, not a random flake.

Not this PR: `test_vlm_input_format.py` is a VLM test, untouched by this `debug_utils`-only diff, and identical to `main`. It cannot be greened from here until the image asset endpoint recovers.

**Reclassifying `base-b-1-gpu-large (2)` as out-of-scope environmental** — same bucket as `build-test` (#30216 `norm.cpp` regression) and the `SGLANG_PRECISION_HF_REPO` nightly-precision lane. No `debug_utils` test has failed in this run; the remaining CUDA lanes (`base-c` multi-GPU) are still draining green.

**Comment by fzyzcjy** [comment]
> 🤖 **Posted autonomously by Claude Code acting on the user's behalf.** Final status: all CUDA lanes green; every remaining red is pre-existing / out-of-scope. Please push back if any call is off.

### ✅ All CUDA lanes green (head `181714fa2` = latest `main` + 4 `debug_utils` commits)

Every NVIDIA lane the `run-ci` label unlocked has settled **SUCCESS** — `base-a`, `base-b` (`1/2-gpu-small/large`, `4-gpu-b200`), and all `base-c` multi-GPU shards (`4-gpu-h100`, `4-gpu-b200`, `4-gpu-gb300`, `8-gpu-h200`, `deepep-*`). The last shard, `base-c-4-gpu-gb300 (1)`, was queued for hours on scarce gb300 hardware and has now run green. **No `debug_utils` test failed at any point.**

- The `vlm` red (`base-b-1-gpu-large (2)`, `PIL.UnidentifiedImageError` in `test_vlm_input_format.py` `setUpClass`) was a transient image-asset outage — the job's re-run passed once the asset recovered.

### Remaining reds — all pre-existing / out of scope for this Python-only diff

| Red | Category |
|---|---|
| `build-test`, `build-test (xeon-gnr, …)` | Pre-existing `main` breakage: `sgl-kernel/csrc/cpu/norm.cpp` `incomplete type NormReduce<…L2Norm, BFloat16>` compile error from #30216. Reproduces on unrelated PRs. `norm.cpp` byte-identical to `main`, not in this diff. |
| `finish` | Aggregate gate cascading from `build-test`. |
| `call-gate / pr-gate` (×2), `pr-test-extra-finish`, `pr-test-amd-extra-finish` | Extra-CI gate — PR not opted into `run-ci-extra` (a user decision). |
| NPU (×4), AMD / mi35x (×3), XPU | Non-CUDA lanes. |

The `debug_utils` change is fully validated: all CUDA lanes green + a prior full `rerun-test`-group run of `debug_utils` was green except the exempt `SGLANG_PRECISION_HF_REPO` nightly-precision lane. This PR is `[DO NOT MERGE]` — its content lands via the split PR chain.

**Comment by fzyzcjy** [comment]
* all ci green
* manual run green https://github.com/sgl-project/sglang/pull/30462#issuecomment-4912109030

**Comment by fzyzcjy** [comment]
> 🤖 **Posted autonomously by Claude Code acting on the user's behalf.** Closing this integration PR now that the split chain is fully open.

Superseded by the split serial-commit PR chain — the four `debug_utils` commits now land as independent PRs, each based on `main`:

1. #30654 — Support per-regex diff-threshold predicates in the tensor comparator (merged)
2. #30655 — Fix rel_diff being nan for bitwise-identical tensors (merged)
3. #30656 — Cap diagnostic detail computation for failing tensors (merged)
4. #30657 — Support grad injection and step override in the dumper's model dump (open)

This `[DO NOT MERGE]` PR was only an integration branch used to run full CI over the cumulative diff. Closing it (branch kept for reference). Nothing here is lost — its net diff was exactly those four commits.
