### PR TITLE
[Bugfix] Hold references to fire-and-forget tasks in disaggregation

### PR DESCRIPTION
**Pull request by noron12234**
## Motivation

Five `asyncio.create_task()` calls in `srt/disaggregation` throw the returned task away. The event loop only keeps a **weak** reference to a running task, so one whose sole reference was the `create_task()` expression can be garbage collected before it finishes — [the asyncio docs call this out explicitly](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task):

> Important: Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn't referenced elsewhere may get garbage collected at any time, even before it's done.

`MMEncoder` in `encode_server.py` already handles this correctly — `self.background_tasks` at line 346, used at 1060, 2022 and 2069. This PR applies that same pattern to the classes in the package that miss it.

| site | task | what a collection costs |
|---|---|---|
| `encode_server.py:2929` `DPDispatcher.start` | `_result_listener` | dispatcher stops consuming worker results |
| `encode_server.py:2930` | `_worker_watchdog` | dead ranks are never detected |
| `encode_server.py:2931` | `_cleanup_stale_mappings` | stale mooncake mappings accumulate |
| `common/conn.py:1721` `CommonKVBootstrapServer._run_server` | `_cleanup_expired_entries` | `room_to_dp_rank` grows without bound |
| `encode_receiver.py:1668` `MMReceiverBase` | the encode dispatch | the encode never happens; the paired `_recv_mm_data` just times out |

The first four are process-lifetime loops, which is the worst case for this bug — nothing else ever holds them.

`encode_receiver.py` deserves a note: the code creates the encode task and then awaits `_recv_mm_data` on a socket, so the task is awaited *indirectly*, never through the task object. A local binding would only cover the happy path — if `wait_for` raises `TimeoutError` the frame unwinds while the encode may still be in flight — so this uses the same instance-level set as the rest.

## Modifications

- `DPDispatcher`: add `self.background_tasks`, register the three loops from `start()`.
- `CommonKVBootstrapServer`: add `self._background_tasks`, register the cleanup loop.
- `MMReceiverBase`: add `self._background_tasks`, register the encode dispatch.

Each uses `set.discard` in the done callback so a double-callback can't raise. No control flow, scheduling order or awaited behaviour changes — the tasks were fire-and-forget before and remain so; they simply can no longer be collected while still running.

## Accuracy Tests

Not applicable — no kernel or model forward code is touched.

## Speed Tests and Profiling

Not applicable. The added work is one `set.add` per task and one `discard` on completion.

## Checklist

- [x] Format your code according to the pre-commit config — run with the pinned versions:
  ```console
  $ isort --check-only <changed files>          # isort 7.0.0
  $ black --check <changed files>               # black 26.1.0
  All done! ✨ 🍰 ✨
  3 files would be left unchanged.
  $ ruff check --select=F401,F821,UP037 <changed files>   # ruff 0.15.1
  All checks passed!
  ```
- [ ] Add unit tests — I did not add one, and would rather say why than leave the box quietly unticked: the failure mode is a garbage-collection race, so a test has to force a GC at a chosen moment and assert a task did *not* vanish, which is flaky by construction. All five call sites also need a live dispatcher / bootstrap server / receiver to reach. Happy to add one if you have a shape in mind.
- [x] Update documentation — not applicable.
- [ ] Accuracy and speed benchmarks — not applicable, see above.
- [x] Follow the SGLang code style guidance.

Found with an AST scan for `create_task` / `ensure_future` results discarded as bare expression statements; after this change that scan reports zero remaining sites in `srt/disaggregation`.

---
### CI States

Latest PR Test (Base): :white_check_mark: [Run #33096305815](https://github.com/sgl-project/sglang/actions/runs/33096305815)
Latest PR Test (Extra): :white_check_mark: [Run #33133118128](https://github.com/sgl-project/sglang/actions/runs/33133118128)
Latest PR Test (AMD ROCm 7.2): :x: [Run #33096306033](https://github.com/sgl-project/sglang/actions/runs/33096306033)

### CODE REVIEW

**Comment by liusy58** [comment]
@noron12234  Thank you for your contribution~ Good fix!

**Review by liusy58 — APPROVED** [review]

**Comment by noron12234** [comment]
@liusy58 Thanks for the review. CI on this one hasn't run yet because the `pr-test` workflows need the `run-ci` label on PRs from forks, so `pr-test-finish` and `pr-test-amd-finish` are sitting at failure without having executed. Could you add the label when you have a moment? Happy to rebase first if that would help.

**Comment by noron12234** [comment]
@liusy58 thanks for adding `run-ci` and merging main in. CI did go red after that, but **the failure was not from this PR** — I merged current main again in 2a99fd3 and it should clear.

The one real failure in `base-a-test-cpu` was:

```
test/registered/unit/managers/test_batch_result_processor_hidden_states.py
AttributeError: 'types.SimpleNamespace' object has no attribute 'think_end_ids'.
Did you mean: 'think_end_id'?
```

That is `managers/`, and this PR only touches three files under `disaggregation/`. The merge you did on 08-02 picked up a point where the test still constructed `SimpleNamespace(think_end_id=...)` while `schedule_batch.py` had already moved to the plural `think_end_ids`. Current main has both sides on the plural form, so re-merging fixes it.

Worth noting the disaggregation test that actually exercises this change did pass in that same run:

```
{"file": "test/registered/unit/disaggregation/test_nixl_sender_failure_cleanup.py", "passed": true, "elapsed": 10}
```

The approval was dismissed by the new commits, so this needs another look when you have a moment.

**Comment by liusy58** [comment]
@noron12234 Never mind, I will push the PR forward

**Review by ShangmingCai — APPROVED** [review]
Looks good.

**Comment by noron12234** [comment]
Digging into the red CI here, since this has two approvals and is only held by the check status.

The only genuine failure in the whole run is one file:

```
✗ FAILED:
  test/registered/xpu/test_xpu_graph.py (timeout after 1200s)
```

Every other test in `stage-b-test-1-gpu-xpu` passed — 9 files, none over 81s. The rest of the red boxes are the `*-finish` / `call-gate` aggregators reporting that one timeout.

This PR touches three files, all under `python/sglang/srt/disaggregation/` (+25/-6): `common/conn.py`, `encode_receiver.py`, `encode_server.py`. It only stores task handles in a module-level set so the event loop's weak references don't let them be collected mid-flight. Nothing in it is reachable from an Intel XPU CUDA-graph test, and the failure mode is a wall-clock timeout rather than an assertion.

Could someone re-run `stage-b-test-1-gpu-xpu`? Happy to rebase onto current main first if that's easier.

File: python/sglang/srt/disaggregation/encode_receiver.py [hunk 1]
```diff
@@ -1754,6 +1757,8 @@ async def recv_mm_data(
                     encode_urls=encode_urls,
                 )
             )
+            self._background_tasks.add(encode_task)
+            encode_task.add_done_callback(self._background_tasks.discard)
```
Comment (dreamer-89) [inline python/sglang/srt/disaggregation/encode_receiver.py]: Thanks @noron12234 for the bug fix. For encode failures, would it be worthwhile to add contextual logging or propagate the error to the waiting request, either here or in a follow-up? Otherwise, asyncio may [log the exception](https://docs.python.org/3/library/asyncio-dev.html#detect-never-retrieved-exceptions) without exposing its cause to the affected request. @liusy58 @ShangmingCai What is your advice on this, would be happy to create a follow up issue on this and fix

**Review by dreamer-89 — APPROVED** [review]
LGTM. I’ll create a follow-up issue to audit the remaining fire-and-forget tasks.

**Comment by dreamer-89** [comment]
> LGTM. I’ll create a follow-up issue to audit the remaining fire-and-forget tasks.

Created https://github.com/sgl-project/sglang/issues/34434

**Comment by liusy58** [comment]
@noron12234 Could you please resolve the conflicts?

**Comment by noron12234** [comment]
@liusy58 Conflicts resolved — rebased onto current `main` (5c3eebf), now `MERGEABLE`.

The rebase was not mechanical, so here is what changed and why:

**`encode_receiver.py` hunk: dropped.** The file moved to `disaggregation/encoder/receiver.py`, and the dispatch there now reads

```python
encode_task = asyncio.create_task(self.encode(...))
recv_task = asyncio.create_task(self._recv_mm_data(...))
done, _ = await asyncio.wait({encode_task, recv_task}, ...)
```

The `asyncio.wait` set already holds a strong reference for the task's whole lifetime, so main is no longer affected. Nothing to add.

**`encode_server.py` hunk: moved to `disaggregation/encoder/runtime.py`.** The file was deleted upstream and `DPDispatcher` landed in `runtime.py`; `start()` there still fires three long-lived loops with no reference held:

```python
asyncio.create_task(self._result_listener())
asyncio.create_task(self._worker_watchdog())
asyncio.create_task(self._cleanup_stale_mappings())
```

Applied there instead. Note `encoder/server.py` already carries a `self.background_tasks` set with the same add/discard idiom, so this follows a pattern already in the tree rather than introducing one.

**`common/conn.py` hunk: unchanged**, applied cleanly (line numbers shifted only).

Diff is down from 3 files to 2. `black --check` clean on both.

**Comment by liusy58** [comment]
@noron12234 Thanks. Let’s wait for the CI to turn green, then we can merge.

**Comment by ShangmingCai** [comment]
Code's fine, and it makes the package consistent with `MMEncoder.background_tasks`.

One thing though: I think failures in the table aren't real, actually. So this is hardening, not a bugfix.
