### PR TITLE
[AMD] support qlen>1 for aiter gluon path for Kimi K3

### PR DESCRIPTION
**Pull request by billishyahao**
## Motivation

This patch is to add qlen>1 support for aiter gluon path.  https://github.com/sgl-project/sglang/pull/34647 only support qlen=1, for other cases, it will fall back to mla asm ps. If you specify the following configs, 

```bash
SGLANG_AITER_HONOR_EXPLICIT_MEM_FRACTION=1 \
SGLANG_USE_AITER=1 \
SGLANG_AITER_K3_OPT=1 \
AITER_FLYDSL_FORCE=1 \
AITER_SITUV2_A8W4=1 \
SGLANG_AITER_MLA_GLUON=1 \
python3 -m sglang.launch_server --model-path /data-models/Kimi-K3 --trust-remote-code \
    --tp-size 8  \
	--prefill-attention-backend aiter \
	--decode-attention-backend aiter \
	--dtype bfloat16 \
	--kv-cache-dtype fp8_e4m3 \
    --cuda-graph-max-bs-decode 32 \
	--max-mamba-cache-size 160 \
	--mem-fraction-static 0.85 \
    --reasoning-parser kimi_k3 \
	--tool-call-parser kimi_k3 \
	--speculative-algorithm DSPARK \
        --speculative-draft-model-path /data-models/RadixArk-Kimi-K3-DSpark \
        --speculative-dspark-block-size 7 \
         --enable-linear-replayssm-spec \
       --speculative-attention-mode decode
```
then will get the server crash:
```bash
[AITER] /sgl-workspace/aiter/aiter_meta/csrc/py_itfs_cu/asm_mla.cu:193 get_heuristic_kernel_mla: cannot get heuristic kernel! q_type:bf16 kv_type:fp8 gqa:16 ps:0 prefill:0 causal:1 qseqlen:8 lse:0 cprr:0
Fatal Python error: Aborted
```

## Modifications

**`layers/attention/aiter_mla_gluon.py`** — `mla_gluon_decode()` introduces `qlen` to decide whether q_nope and q_pe needs to be viewed

**`layers/attention/aiter_backend.py`** — remove `max_q_len == 1` gate to allow qlen >1 path being activated for dspark 

**`distributed/parallel_state.py`** — DSPARK's in-graph sampler use broadcast inside a CUDA graph, which is crashed by using torch api during cuda graph capture. Change it to pynccl.

**`test/registered/attention/test_aiter_gluon_h12_fp8.py`** — renamed from `test_mla_gluon_h12_fp8.py` to make the name more clear and rewritten (17 cases, mocked, no kernel invoked)

## Accuracy Tests

python benchmark/gsm8k/bench_sglang.py --num-shots 5 --num-questions 1300 --parallel 64 --port 8100

Accuracy: 0.953
Invalid: 0.001
Latency: 100.714 s
Output throughput: 1296.612 token/s

## Checklist

- [x] Format your code according to the [Format code with pre-commit](https://docs.sglang.io/developer_guide/contribution_guide.html#format-code-with-pre-commit).
- [ ] Add unit tests according to the [Run and add unit tests](https://docs.sglang.io/developer_guide/contribution_guide.html#run-and-add-unit-tests).
- [ ] Update documentation according to [Write documentations](https://docs.sglang.io/developer_guide/contribution_guide.html#write-documentations).
- [ ] Provide accuracy and speed benchmark results according to [Test the accuracy](https://docs.sglang.io/developer_guide/contribution_guide.html#test-the-accuracy) and [Benchmark the speed](https://docs.sglang.io/developer_guide/contribution_guide.html#benchmark-the-speed).
- [x] Follow the SGLang code style [guidance](https://docs.sglang.io/developer_guide/contribution_guide.html#code-style-guidance).

## Review and Merge Process

1. Ping Merge Oncalls to start the process. See the [PR Merge Process](https://github.com/sgl-project/sglang/blob/main/.github/MAINTAINER.md#pull-request-merge-process).
2. Get approvals from [CODEOWNERS](https://github.com/sgl-project/sglang/blob/main/.github/CODEOWNERS) and other reviewers.
3. Trigger CI tests with [comments](https://docs.sglang.io/developer_guide/contribution_guide.html#how-to-trigger-ci-tests) or contact authorized users to do so.
   - Common commands include `/tag-and-rerun-ci`, `/tag-run-ci-label`, `/rerun-failed-ci`
4. After green CI and required approvals, ask Merge Oncalls or people with Write permission to merge the PR.

---
### CI States

Latest PR Test (Base): :x: [Run #34074956295](https://github.com/sgl-project/sglang/actions/runs/34074956295)
Latest PR Test (Extra): :x: [Run #34074956107](https://github.com/sgl-project/sglang/actions/runs/34074956107)
Latest PR Test (AMD ROCm 7.2): :hourglass_flowing_sand: [Run #34074956212](https://github.com/sgl-project/sglang/actions/runs/34074956212)

### CODE REVIEW

**Review by HaiShaw — APPROVED** [review]

**Comment by billishyahao** [comment]
re-trigger ci due to 
https://github.com/sgl-project/sglang/actions/runs/33819121460/job/100859975831
```bash
  Error: A major update has landed on `main`. All PRs must rebase onto the latest `main` before CI will run.
  Error: Required base commit: `a5f07b1241fc` (your PR is `diverged` relative to this commit).
```

**Comment by billishyahao** [comment]
NV and CPU test are passed. https://github.com/sgl-project/sglang/actions/runs/33998322033/job/101393878232?pr=37601

**Comment by HaiShaw** [comment]
HIP/AITER gated

**Comment by mmangkad** [comment]
Why was base-a failure https://github.com/sgl-project/sglang/actions/runs/34074956295/job/101599269921#step:15:1084 ignored here?

**Comment by billishyahao** [comment]
Hi @mmangkad  This base-a failure 

```
======================================================================
ERROR: test_env_disable_not_ready (__main__.TestMlaGluonCapability)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/sglang/sglang/test/registered/attention/test_mla_gluon_h12_fp8.py", line 20, in setUp
    from sglang.srt.layers.attention.aiter_mla_gluon import (
ImportError: cannot import name 'reset_mla_gluon_state_for_test' from 'sglang.srt.layers.attention.aiter_mla_gluon' (/home/runner/work/sglang/sglang/python/sglang/srt/layers/attention/aiter_mla_gluon.py)
```

comes from stale unittest test/registered/attention/test_mla_gluon_h12_fp8.py introduced by #34647 which is renamed and replaced by test/registered/attention/test_aiter_gluon_h12_fp8.py (`I made this name to let it more specific to aiter`)
through initial commits 
https://github.com/sgl-project/sglang/pull/37601/changes/df4ada89c551367fd41d3a3348107df63f229a88

but then rename behaviour tracking is lost after several rebasing to main.  It was reverted by 511e75fc5e Merge remote-tracking branch 'sgl/main' into gluon_dspark. This is unexpected.

Thanks for dropping it https://github.com/sgl-project/sglang/pull/38259
