### ISSUE TITLE
[Feature] Set outlines and xgrammar as addtional dependency

### ISSUE THREAD

**Issue by zhaochenyang20** [sgl-project/sglang#2549]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

I am trying to integrate SGLang and vllm into OpenRLHF. For the grammar backend, could we set it as additional requirements, i.e. import it when we use it? Like:

```python

def __init__():
    if use_constrained_decoding:
        if grammar_backend == "xgrammar":
            import xgrammar
            xgrammar.function()
        if grammar_backend == "outlines":
            import outlines
            outlines.function()
```

This to avoid the version conflicts with vllm.

### Related resources

No such.

**Comment by zhaochenyang20** [comment]
ImportError: cannot import name 'build_regex_from_schema' from 'outlines.fsm.json_schema' (/opt/dlami/nvme/chenyang/miniconda3/envs/sglang/lib/python3.11/site-packages/outlines/fsm/json_schema.py)

0.1.11  outlines with sglang.

**Comment by zhaochenyang20** [comment]
related to https://github.com/sgl-project/sglang/issues/2550

**Comment by shuaills** [comment]
Currently, there is a compatibility issue when using vllm, sglang, and outlines together. While sglang and vllm 0.6.3.post1 work with torch 2.4, newer versions of vllm (0.6.4+) require torch 2.5. Additionally, outlines has version-specific dependencies that conflict with this setup, making it challenging to use all three libraries simultaneously in the same environment.
