### PR TITLE
[AMD] Add MiniMax-M2.7 accuracy and performance nightly tests

### PR DESCRIPTION
**Pull request by michaelzhang-ai**
## Summary

- Add MiniMax-M2.7 (https://huggingface.co/MiniMaxAI/MiniMax-M2.7) accuracy (GSM8K 5-shot) and performance (`bench_one_batch`) nightly CI tests for AMD MI30x (MI325/MI300X)
- MiniMax-M2.7 shares the same `MiniMaxM2ForCausalLM` architecture as M2.5 with identical MoE config (256 experts, 8 active), using TP8+EP8 server configuration with `aiter` attention backend
- Replace M2.5 nightly CI jobs with M2.7 on MI30x (M2.5 test files kept in repo, just not run in nightly)
- MI35x test files created but not wired to nightly jobs yet (pending more MI35x runners)
- Fix broken import in `minimax_m2.py`: `get_bool_env_var` was imported from `sglang.srt.distributed` but is defined in `sglang.srt.utils.common` (introduced by #20673, breaks all MiniMax M2 models on current main — [M2.5 also fails](https://github.com/sgl-project/sglang/actions/runs/24358226838/job/71130716099))

### Test Files
| File | Platform | Type | Suite | Nightly |
|------|----------|------|-------|---------|
| `test/registered/amd/accuracy/mi30x/test_minimax_m27_eval_amd.py` | MI30x | Accuracy | `nightly-amd-accuracy-8-gpu-minimax-m27` | :white_check_mark: active |
| `test/registered/amd/perf/mi30x/test_minimax_m27_perf_amd.py` | MI30x | Perf | `nightly-perf-8-gpu-minimax-m27` | :white_check_mark: active |
| `test/registered/amd/accuracy/mi35x/test_minimax_m27_eval_mi35x.py` | MI35x | Accuracy | `nightly-amd-8-gpu-mi35x-minimax-m27` | :no_entry_sign: not wired (pending runners) |
| `test/registered/amd/perf/mi35x/test_minimax_m27_perf_mi35x.py` | MI35x | Perf | `nightly-perf-8-gpu-mi35x-minimax-m27` | :no_entry_sign: not wired (pending runners) |

### Workflow Changes
Both `nightly-test-amd.yml` and `nightly-test-amd-rocm720.yml` updated:
- Remove M2.5 MI30x + MI35x job definitions, dropdown options, and `check-all-jobs.needs` entries
- Add M2.7 MI30x job definitions (accuracy + perf combined), dropdown options, and `check-all-jobs.needs` entries

### Bug Fix
`python/sglang/srt/models/minimax_m2.py`: moved `get_bool_env_var` import from `sglang.srt.distributed` to `sglang.srt.utils.common`. Without this fix, the native MiniMax M2 model fails to register during import, causing fallback to the transformers wrapper which crashes on `config.rope_parameters`.

## CI Results (all pass)

- **Default ROCm**: https://github.com/sgl-project/sglang/actions/runs/24362746024
- **ROCm 7.2**: https://github.com/sgl-project/sglang/actions/runs/24362746633

| Job | Status |
|-----|--------|
| `nightly-8-gpu-minimax-m27` (MI30x) | :white_check_mark: passed |
| `nightly-8-gpu-mi35x-minimax-m27` (MI35x) | :white_check_mark: passed |
| `nightly-8-gpu-minimax-m27-rocm720` (MI30x, ROCm 7.2) | :white_check_mark: passed |
| `nightly-8-gpu-mi35x-minimax-m27-rocm720` (MI35x, ROCm 7.2) | :white_check_mark: passed |

## MiniMax-M2.7 Accuracy Results (GSM8K 5-shot, 200 questions)

| Platform | Accuracy | Threshold | Status |
|----------|----------|-----------|--------|
| MI30x (MI325) | 0.935 | 0.93 | PASS |
| MI35x | 0.960 | 0.93 | PASS |

### MI30x (MI325)

| batch size | input len | latency (s) | input throughput (tok/s) | output throughput (tok/s) | ITL (ms) |
| ---------- | --------- | ----------- | ------------------------ | ------------------------- | -------- |
| 1 | 4096 | 6.07 | 8704.99 | 91.39 | 10.94 |
| 8 | 4096 | 8.16 | 25272.66 | 597.08 | 13.40 |
| 16 | 4096 | 9.13 | 44146.36 | 1072.14 | 14.92 |
| 64 | 4096 | 14.11 | 60731.52 | 3347.34 | 19.12 |

### MI35x

| batch size | input len | latency (s) | input throughput (tok/s) | output throughput (tok/s) | ITL (ms) |
| ---------- | --------- | ----------- | ------------------------ | ------------------------- | -------- |
| 1 | 4096 | 4.35 | 44039.82 | 120.32 | 8.31 |
| 8 | 4096 | 5.54 | 80291.27 | 798.56 | 10.02 |
| 16 | 4096 | 6.53 | 81585.24 | 1430.34 | 11.19 |
| 64 | 4096 | 10.99 | 85850.02 | 4129.25 | 15.50 |

### Comparison vs M2.5 (MI30x, Apr 12 nightly)

| batch size | M2.5 output tput | M2.7 output tput | M2.5 ITL | M2.7 ITL |
| ---------- | ---------------- | ---------------- | -------- | -------- |
| 1 | 91.83 tok/s | 91.39 tok/s | 10.89 ms | 10.94 ms |
| 8 | 598.30 tok/s | 597.08 tok/s | 13.37 ms | 13.40 ms |
| 16 | 1075.49 tok/s | 1072.14 tok/s | 14.88 ms | 14.92 ms |
| 64 | 3033.94 tok/s | **3347.34 tok/s (+10.3%)** | 21.09 ms | **19.12 ms (-9.3%)** |

Performance is on par at small batch sizes. At batch_size=64, M2.7 shows +10% output throughput and -9% ITL, likely due to native FP8 quantization.

### CODE REVIEW

**Comment by michaelzhang-ai** [comment]
## CI Runs Triggered

- **Default ROCm**: https://github.com/sgl-project/sglang/actions/runs/24360325074
  - Jobs: `nightly-8-gpu-minimax-m27`, `nightly-8-gpu-mi35x-minimax-m27`
- **ROCm 7.2**: https://github.com/sgl-project/sglang/actions/runs/24360325699
  - Jobs: `nightly-8-gpu-minimax-m27-rocm720`, `nightly-8-gpu-mi35x-minimax-m27-rocm720`

**Comment by michaelzhang-ai** [comment]
## CI Runs v2 (with import fix + M2.5 replaced by M2.7)

Root cause of v1 failure: `minimax_m2.py` imported `get_bool_env_var` from `sglang.srt.distributed` but it's defined in `sglang.srt.utils.common`. This broke native model registration, causing fallback to transformers wrapper which crashed on `rope_parameters`. Fixed in latest push.

Changes in this push:
- Fix `minimax_m2.py` import bug (`get_bool_env_var` → correct module)
- Remove M2.5 nightly CI jobs (M2.7 replaces them); M2.5 test files kept in repo

- **Default ROCm**: https://github.com/sgl-project/sglang/actions/runs/24362746024
  - Jobs: `nightly-8-gpu-minimax-m27`, `nightly-8-gpu-mi35x-minimax-m27`
- **ROCm 7.2**: https://github.com/sgl-project/sglang/actions/runs/24362746633
  - Jobs: `nightly-8-gpu-minimax-m27-rocm720`, `nightly-8-gpu-mi35x-minimax-m27-rocm720`

**Review by HaiShaw — CHANGES_REQUESTED** [review]
@michaelzhang-ai Please not to accurate mi35x tests for the model not on mxfp4 for now, keep the test cases is fine, just not to run until later with more mi35x runners in place.

And do same for other models.

**Comment by michaelzhang-ai** [comment]
> @michaelzhang-ai Please not to accurate mi35x tests for the model not on mxfp4 for now, keep the test cases is fine, just not to run until later with more mi35x runners in place.
> 
> And do same for other models.

updated.

**Comment by michaelzhang-ai** [comment]
## Re: revert of `get_bool_env_var` import fix

@HaiShaw The import fix for `minimax_m2.py` is necessary — `get_bool_env_var` is **not** exported from `sglang.srt.distributed`. It's defined in `sglang.srt.utils.common` and re-exported via `sglang.srt.utils`.

**Evidence:**
- `sglang.srt.distributed/__init__.py` has 0 references to `get_bool_env_var` (both on this branch and latest `main`)
- Other files in the codebase use the correct path:
  - `sglang/srt/distributed/device_communicators/custom_all_reduce.py` → `from sglang.srt.utils import get_bool_env_var`
  - `sglang/srt/utils/hf_transformers_utils.py` → `from sglang.srt.utils import get_bool_env_var`
- The broken import was introduced by #20673 (`[Feature][JIT Kernel] Fused TP QK norm For Minimax`)
- Without this fix, **both M2.5 and M2.7 fail** on current `main`: [M2.5 nightly failure](https://github.com/sgl-project/sglang/actions/runs/24358226838/job/71130716099)

**Failure chain:**
1. `from sglang.srt.distributed import get_bool_env_var` → `ImportError`
2. `minimax_m2.py` fails to import → native `MiniMaxM2ForCausalLM` not registered in `ModelRegistry`
3. Falls back to `TransformersForCausalLM` wrapper → `AutoModel.from_config()` → `MiniMaxM2RotaryEmbedding.__init__`
4. `self.config.rope_parameters["rope_type"]` → `AttributeError: 'MiniMaxM2Config' object has no attribute 'rope_parameters'`

Restored the fix in commit 49e42d367 with a comment explaining why it's needed.

**Review by HaiShaw — APPROVED** [review]

**Comment by HaiShaw** [comment]
@amd-bot ci-status
