### PR TITLE
Support piecewise CUDA graph with NSA

### PR DESCRIPTION
**Pull request by nvjullin**
## Motivation

GLM-5/DSV3.2 currently doesn't allow piecewise CUDA graph due to incompatibilities in NSA attention backend and NSA indexer. This commit fixes the incompatibilities on the conditions
1. is not context parallel
2. is on CUDA

`_store_index_k_cache` and `_get_topk_ragged` are excluded from CUDA graph for now, will revisit whether they can be in CUDA graph in a future PR.

Benchmark results
image

Benchmark command
```bash
python3 bench_serving/benchmark_serving.py --backend sglang --host localhost --port 8080 --model zai-org/GLM-5-FP8 --num-prompts 1024 --ignore-eos --max-concurrency 128 --random-input-len 1024 --random-output-len 1024 --random-range-ratio 0.8 --use-chat-template --dataset-name random --save-result --result-filename results/concurrency_128.json
```

## Modifications

In NSA code path:
1. Remove/fix torch.compile incompatible constructs
2. Correctly handling padding rows

## Accuracy Tests

```bash
python3 -m sglang.test.run_eval --base-url http://localhost:8080 --model zai-org/GLM-5-FP8 --num-threads 128 --eval-name gpqa --max-tokens 128000 --num-examples 198 --repeat 8 --top-p 0.95 --temperature 1.0 --thinking-mode glm-45
```

Repeat: 8, mean: 0.862
Scores: ['0.848', '0.874', '0.874', '0.859', '0.848', '0.843', '0.869', '0.879']

## Checklist

- [ ] Format your code according to the [Format code with pre-commit](https://docs.sglang.io/developer_guide/contribution_guide.html#format-code-with-pre-commit).
- [ ] Add unit tests according to the [Run and add unit tests](https://docs.sglang.io/developer_guide/contribution_guide.html#run-and-add-unit-tests).
- [ ] Update documentation according to [Write documentations](https://docs.sglang.io/developer_guide/contribution_guide.html#write-documentations).
- [ ] Provide accuracy and speed benchmark results according to [Test the accuracy](https://docs.sglang.io/developer_guide/contribution_guide.html#test-the-accuracy) and [Benchmark the speed](https://docs.sglang.io/developer_guide/contribution_guide.html#benchmark-the-speed).
- [ ] Follow the SGLang code style [guidance](https://docs.sglang.io/developer_guide/contribution_guide.html#code-style-guidance).

## Review and Merge Process

1. Ping Merge Oncalls to start the process. See the [PR Merge Process](https://github.com/sgl-project/sglang/blob/main/.github/MAINTAINER.md#pull-request-merge-process).
2. Get approvals from [CODEOWNERS](https://github.com/sgl-project/sglang/blob/main/.github/CODEOWNERS) and other reviewers.
3. Trigger CI tests with [comments](https://docs.sglang.io/developer_guide/contribution_guide.html#how-to-trigger-ci-tests) or contact authorized users to do so.
   - Common commands include `/tag-and-rerun-ci`, `/tag-run-ci-label`, `/rerun-failed-ci`
4. After green CI and required approvals, ask Merge Oncalls or people with Write permission to merge the PR.

---
### CI States

Latest PR Test (Base): :no_entry_sign: [Run #26311925143](https://github.com/sgl-project/sglang/actions/runs/26311925143)
Latest PR Test (Extra): :no_entry_sign: [Run #26311925079](https://github.com/sgl-project/sglang/actions/runs/26311925079)

### CODE REVIEW

File: python/sglang/srt/server_args.py [hunk 1]
```diff
@@ -2933,22 +2937,6 @@ def _handle_moe_kernel_config(self):
                 self.ep_size == 1
             ), "FP8/MXFP8 Cutlass MoE is only supported with ep_size == 1"
 
-        # TODO(yuwei): Fix piecewise cuda graph support for bypassed topk MoE backends.
-        # Exception: GptOssForCausalLM wraps the entire MoE block in its own
```
Comment (Fridge003) [inline python/sglang/srt/server_args.py:3187]: Rather than removing this if block, we can add an exemption for dsa models here

File: python/sglang/srt/layers/attention/nsa_backend.py [hunk 2]
```diff
@@ -2101,7 +2104,24 @@ def _forward_trtllm(
...
+            dtype=torch.bfloat16,
+            device=q.device,
+        )
+        out_kernel = out
+        if forward_batch.forward_mode.is_extend_without_speculative():
+            # Piecewise CUDA graph pads tensors (q, block_tables) to static_num_tokens
+            # but seq_lens covers only the real batch. Slice to real tokens to avoid
+            # invalid block index accesses on padding rows.
+            # out is kept at full batch_size for the caller; out_kernel is the slice the kernel writes into.
+            real_batch_size = seq_lens.shape[0]
```
Comment (Fridge003) [inline python/sglang/srt/layers/attention/nsa_backend.py]: Looks like PCG is only enabled on trtllm nsa backend. We need to add assertion at server_args.py as warning

File: python/sglang/srt/layers/attention/nsa/nsa_indexer.py [hunk 3]
```diff
@@ -11,6 +11,10 @@
     can_use_nsa_fused_store,
```
Comment (Fridge003) [inline python/sglang/srt/layers/attention/nsa/nsa_indexer.py]: Will it be easier if we create a mixin class/subclass for PCG indexer, so we don't need to do a lot of inline if-else condition here

**Comment by Fridge003** [comment]
We can add a PCG test for GLM-5-fp4, registered as stage-c-test-4-gpu-b200

**Comment by Fridge003** [comment]
For the gpqa accuracy test, please make sure temperature is 1.0, top_p is 0.95, `--thinking-mode glm-45` is appended.
0.813 looks lower than expectation.

We also need another accuracy test for AIME2025, with the instruction here https://docs.sglang.io/docs/basic_usage/deepseek_v32#accuracy-test-with-aime-2025.
The number of turns can be larger than 4, since AIME2025 fluctuate a lot. The larger the better

File: python/sglang/srt/server_args.py (hunk 1 above)
Comment (nvjullin) [reply python/sglang/srt/server_args.py:3187]: The problem here is torch.compile compatibility instead of PCG compatibility. The fix was in sglang before the removal of the block, and it seems general to all models. Do you still think we need to guard it?

https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/layers/moe/fused_moe_triton/layer.py#L978-L1003

https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/layers/moe/fused_moe_triton/layer.py#L1176-L1200

File: python/sglang/srt/layers/attention/nsa_backend.py (hunk 2 above)
Comment (nvjullin) [reply python/sglang/srt/layers/attention/nsa_backend.py]: Good catch, this is redundant code from a previous iteration. The slicing happens in `radix_attention.py` and should apply for all backends. Fixed.

File: python/sglang/srt/layers/attention/nsa/nsa_indexer.py (hunk 3 above)
Comment (nvjullin) [reply python/sglang/srt/layers/attention/nsa/nsa_indexer.py]: There are 6 `if _is_cuda` in nsa_indexer.py out of 1755 LoC, so I think it's not particularly egregious right now.

Side note: I personally hate mixins and subclassing. They make statically tracing code so much harder because you are doing dynamic dispatch. I understand they solve excessive branching, but they introduce their own problems. It's a tradeoff.

**Comment by nvjullin** [comment]
> We can add a PCG test for GLM-5-fp4, registered as stage-c-test-4-gpu-b200

Added gsm8k test. I understand it doesn't catch all indexer bugs, but it runs in ~10min. Let me know if you want a different test.

**Comment by nvjullin** [comment]
I'll rerun gpqa, but there's some discrepancy between testing methodology. Do we want to iron those out before this PR merges?

**Comment by nvjullin** [comment]
@Fridge003 Comments have been addressed, can you review this again?

File: python/sglang/srt/layers/attention/nsa/nsa_indexer.py (hunk 3 above)
Comment (Fridge003) [reply python/sglang/srt/layers/attention/nsa/nsa_indexer.py]: Cool

**Review by Fridge003 — APPROVED** [review]

**Review by Fridge003 — DISMISSED** [review]
@nvjullin Please take a look at this failure 
https://github.com/sgl-project/sglang/actions/runs/25697350075/job/75487272167?pr=23351

**Comment by nvjullin** [comment]
https://github.com/sgl-project/sglang/actions/runs/25697350075/job/75487272167?pr=23351
is caused by running `attn_mqa` in PCG path when it should've been dispatched to MHA (due to short seq lens).
Checking if dispatch can be done, or disable MHA if not.

**Comment by nvjullin** [comment]
MHA fast path not viable, forcing it off.

File: test/registered/piecewise_cuda_graph/test_pcg_glm5_fp4.py [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+from sglang.test.ci.ci_register import register_cuda_ci
+from sglang.test.run_eval import run_eval
+from sglang.test.test_utils import (
+    DEFAULT_TIMEOUT_FOR_SERVER_LAUNCH,
+    DEFAULT_URL_FOR_TEST,
+    CustomTestCase,
+    popen_launch_server,
+)
+
+register_cuda_ci(est_time=900, suite="stage-c-test-4-gpu-b200")
```
Comment (Fridge003) [inline test/registered/piecewise_cuda_graph/test_pcg_glm5_fp4.py]:
```suggestion
register_cuda_ci(est_time=900, suite="base-c-test-4-gpu-b200")
```

**Comment by nvpohanh** [comment]
Pipeline failure is:

```
Attempt 1 failure summary:
  FAILED sglang/multimodal_gen/test/server/test_server_2_gpu.py::TestDiffusionServerTwoGpu::test_diffusion_generation[ltx_2.3_two_stage_t2v_2gpus] - Failed: Diffusion testcase 'ltx_2.3_two_stage_t2v_2gpus' failed 1 check(s):
  [performance]
  Validation failed for 'Median Denoise Step'.
  Actual:   322.1165ms
  Expected: 179.2600ms
  Limit:    215.1120ms (rel_tol: 20.0%, abs_pad: 20.0ms)
  assert 322.1165332943201 <= 215.112
```
https://github.com/sgl-project/sglang/actions/runs/26115359531/job/76868140554?pr=23351

Doesn't seem to be caused by this PR

**Review by Fridge003 — APPROVED** [review]

**Comment by nvjullin** [comment]
Conflicts resolved, quick accuracy test passed. I have no way of preserving git history, the conflicts are too large.

**Comment by nvpohanh** [comment]
@nvjullin please merge/rebase latest ToT main to fix the CI issue. thanks!

File: test/registered/piecewise_cuda_graph/test_pcg_glm5_fp4.py (hunk 4 above)
Comment (Fridge003) [inline test/registered/piecewise_cuda_graph/test_pcg_glm5_fp4.py]:
```suggestion
register_cuda_ci(est_time=900, stage="base-c", runner_config="4-gpu-b200")
```

**Comment by nvpohanh** [comment]
```
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/layers/utils/multi_platform.py", line 83, in forward
    return self._forward_method(*args, **kwargs)
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/layers/attention/dsa/dsa_indexer.py", line 1509, in forward_cuda
    k_cache_and_topk_result(
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 1269, in __call__
    return self._op(*args, **kwargs)
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/layers/attention/dsa/dsa_indexer.py", line 122, in k_cache_and_topk_result
    metadata = forward_batch.attn_backend.get_indexer_metadata(
AttributeError: 'ForwardBatch' object has no attribute 'attn_backend'
```
https://github.com/sgl-project/sglang/actions/runs/26256885165/job/77291831227?pr=23351
@nvjullin seeing this failure

**Comment by nvjullin** [comment]
Failure caused by bad merge from https://github.com/sgl-project/sglang/pull/25983. Fixed.

**Comment by nvpohanh** [comment]
```
[2026-05-22 04:54:32 TP6] Piecewise CUDA Graph failed with error: Tensor match failed for Tensor<8>[strides=<1>, dtype=int64, device=cuda:6] at /actions-runner/_work/sglang/sglang/python/sglang/jit_kernel/csrc/dsa/fused_store_index_cache.cuh:107
- Root cause: Size mismatch for shape#0('num_tokens'): expected 6 but got 8
Piecewise CUDA Graph is enabled by default as an experimental feature.
To work around this error, add --disable-piecewise-cuda-graph to your launch command.
Please report this issue at https://github.com/sgl-project/sglang/issues/new/choose
[2026-05-22 04:54:32 TP6] Scheduler hit an exception: Traceback (most recent call last):
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/managers/scheduler.py", line 3811, in run_scheduler_process
    scheduler.run_event_loop()
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/managers/scheduler.py", line 1507, in run_event_loop
    dispatch_event_loop(self)
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/managers/scheduler.py", line 3680, in dispatch_event_loop
    scheduler.event_loop_overlap()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/managers/scheduler.py", line 1567, in event_loop_overlap
    batch_result = self.run_batch(batch)
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/managers/scheduler.py", line 2865, in run_batch
    batch_result = self.model_worker.forward_batch_generation(
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/managers/tp_worker.py", line 472, in forward_batch_generation
    out = self.model_runner.forward(
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/model_executor/model_runner.py", line 3182, in forward
    output = self._forward_raw(
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/model_executor/model_runner.py", line 3314, in _forward_raw
    ret, can_run_graph = self.forward_extend(
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/model_executor/model_runner.py", line 3075, in forward_extend
    ret = self.piecewise_cuda_graph_runner.replay(forward_batch, **kwargs)
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/model_executor/piecewise_cuda_graph_runner.py", line 805, in replay
    output = self.model_runner.model.forward(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/models/deepseek_v2.py", line 2524, in forward
    hidden_states = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/compilation/compile.py", line 195, in trampoline
    return compiled_callable(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 1024, in compile_wrapper
    return fn(*args, **kwargs)
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/models/deepseek_v2.py", line 2216, in forward
    def forward(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 472, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 1263, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 949, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 461, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 447, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.1122", line 1227, in forward
    submod_1 = self.submod_1(getitem, s72, getitem_1, getitem_2, getitem_3);  getitem = getitem_1 = getitem_2 = submod_1 = None
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 949, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 461, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py", line 447, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.1124", line 5, in forward
    k_cache_and_topk_result = torch.ops.sglang.k_cache_and_topk_result(layer_id = 0, key = key_1, q_fp8 = y, weights = weights, topk_result = topk_result);  key_1 = y = weights = topk_result = k_cache_and_topk_result = None
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 1269, in __call__
    return self._op(*args, **kwargs)
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/layers/attention/dsa/dsa_indexer.py", line 127, in k_cache_and_topk_result
    indexer._store_index_k_cache(
  File "/actions-runner/_work/sglang/sglang/python/sglang/srt/layers/attention/dsa/dsa_indexer.py", line 1200, in _store_index_k_cache
    fused_store_index_k_cache(
  File "/actions-runner/_work/sglang/sglang/python/sglang/jit_kernel/fused_store_index_cache.py", line 105, in fused_store_index_k_cache
    module.fused_store_index_k_cache(key, index_k_with_scale, out_cache_loc)
  File "python/tvm_ffi/cython/function.pxi", line 929, in tvm_ffi.core.Function.__call__
RuntimeError: Tensor match failed for Tensor<8>[strides=<1>, dtype=int64, device=cuda:6] at /actions-runner/_work/sglang/sglang/python/sglang/jit_kernel/csrc/dsa/fused_store_index_cache.cuh:107
- Root cause: Size mismatch for shape#0('num_tokens'): expected 6 but got 8
```
https://github.com/sgl-project/sglang/actions/runs/26265766989/job/77308576707?pr=23351
@nvjullin Looks like real failures caused by this change.

**Comment by nvjullin** [comment]
Fixed `out_cache_loc`, same bad merge from above. Quick accuracy test shows it's correct.

**Comment by Fridge003** [comment]
Other tests are OK https://github.com/sgl-project/sglang/pull/23351/checks?sha=632b381033e3ea1faf5d0561a12ff6b6f1b4fa0a
Now fixing the newly added pcg test

File: python/sglang/srt/server_args.py (hunk 1 above)
Comment (mmangkad) [reply python/sglang/srt/server_args.py:3187]: I think we still need the guard: the custom op fixes Dynamo traceability, but it does not guarantee every `flashinfer_trtllm` bypassed-topk kernel is safe under PCG capture/replay. I opened a PR to restore the guard and add the exemption only for DSA models / already-supported paths.

#26718
