### PR TITLE
[MLX] Restore prefill_aware_swa on MlxModelRunnerStub

### PR DESCRIPTION
**Pull request by Toufupi**
## Motivation

Fix MLX backend startup crash introduced by #29186 (baidu unlimited-ocr). That PR added a `prefill_aware_swa` attribute to `ModelRunner.__init__` and reads it from `scheduler._get_new_batch_prefill_raw`, but `MlxModelRunnerStub` overrides `load_model()` without copying the attribute. The first prefill batch on Apple Silicon crashes with `AttributeError: 'MlxModelRunnerStub' object has no attribute 'prefill_aware_swa'`, blocking all MLX server startups.

## Modifications

- `python/sglang/srt/hardware_backend/mlx/model_runner_stub.py`: add `self.prefill_aware_swa = False` in `load_model()` to mirror the base class attribute.

1 file changed, 1 insertion(+).
## Checklist

- [ ] Format your code according to the [Format code with pre-commit](https://docs.sglang.io/developer_guide/contribution_guide.html#format-code-with-pre-commit).
- [ ] Add unit tests according to the [Run and add unit tests](https://docs.sglang.io/developer_guide/contribution_guide.html#run-and-add-unit-tests).
- [ ] Update documentation according to [Write documentations](https://docs.sglang.io/developer_guide/contribution_guide.html#write-documentations).
- [ ] Provide accuracy and speed benchmark results according to [Test the accuracy](https://docs.sglang.io/developer_guide/contribution_guide.html#test-the-accuracy) and [Benchmark the speed](https://docs.sglang.io/developer_guide/contribution_guide.html#benchmark-the-speed).
- [ ] Follow the SGLang code style [guidance](https://docs.sglang.io/developer_guide/contribution_guide.html#code-style-guidance).

## Review and Merge Process

1. Ping Merge Oncalls to start the process. See the [PR Merge Process](https://github.com/sgl-project/sglang/blob/main/.github/MAINTAINER.md#pull-request-merge-process).
2. Get approvals from [CODEOWNERS](https://github.com/sgl-project/sglang/blob/main/.github/CODEOWNERS) and other reviewers.
3. Trigger CI tests with [comments](https://docs.sglang.io/developer_guide/contribution_guide.html#how-to-trigger-ci-tests) or contact authorized users to do so.
   - Common commands include `/tag-and-rerun-ci`, `/tag-run-ci-label`, `/rerun-failed-ci`
4. After green CI and required approvals, ask Merge Oncalls or people with Write permission to merge the PR.

---
### CI States

Latest PR Test (Base): :x: [Run #28309785778](https://github.com/sgl-project/sglang/actions/runs/28309785778)
Latest PR Test (Extra): :x: [Run #28309785724](https://github.com/sgl-project/sglang/actions/runs/28309785724)

### CODE REVIEW

**Comment by yeahdongcn** [comment]
Close as duplicate to: https://github.com/sgl-project/sglang/pull/29681
