### PR TITLE
[bugfix]hicache bench_long_context.py run failed

### PR DESCRIPTION
**Pull request by zhannngchen**
## Motivation

fix hicache bench_long_context.py failure
```
Traceback (most recent call last):
  File "/home/zhangchen50/sglang-main/benchmark/hicache/bench_long_context.py", line 104, in <module>
    performance_data = ContextWorkloadGenerator(args).run()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhangchen50/sglang-main/benchmark/hicache/bench_multiturn.py", line 513, in run
    if self.enable_round_barrier:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ContextWorkloadGenerator' object has no attribute 'enable_round_barrier'
```

introduced by #10203

## Checklist

- [x] Format your code according to the [Format code with pre-commit](https://docs.sglang.ai/developer_guide/contribution_guide.html#format-code-with-pre-commit).
- [ ] Add unit tests according to the [Run and add unit tests](https://docs.sglang.ai/developer_guide/contribution_guide.html#run-and-add-unit-tests).
- [ ] Update documentation according to [Write documentations](https://docs.sglang.ai/developer_guide/contribution_guide.html#write-documentations).
- [ ] Provide accuracy and speed benchmark results according to [Test the accuracy](https://docs.sglang.ai/developer_guide/contribution_guide.html#test-the-accuracy) and [Benchmark the speed](https://docs.sglang.ai/developer_guide/contribution_guide.html#benchmark-the-speed).

### CODE REVIEW

**Comment by zhannngchen** [comment]
@ykwd @xiezhq-hermann could you help to review this fix? thanks

**Review by acelyc111 — APPROVED** [review]

**Comment by ykwd** [comment]
Sorry, I wasn’t aware that the multi-turn change would affect other tests. This fix looks good to me.

**Review by xiezhq-hermann — APPROVED** [review]
