### PR TITLE
[Bugfix] Radix-aware resume

### PR DESCRIPTION
**Pull request by HsuYenMin**
## Summary

Two-part fix for a decode-scheduler crash under retraction with the decode-side radix cache, plus the follow-up efficiency fix requested in review (@hzh0425):

1. **Guard** (`6340470`) — stop `cache_unfinished_req` from crashing when a retracted request resumes with `req.last_node is None`.
2. **Radix-aware resume** (`70339467`) — on resume, reuse the request's on-device radix prefix and restore only the missing suffix from the CPU copy, instead of a full re-allocation + full restore.

## Root Cause

In PD-disaggregated decode with the decode-side radix cache, a request retracted under KV pressure has `req.last_node` cleared by `reset_for_retract()`. On resume, the decode "prebuilt" path (`process_prebuilt → maybe_cache_unfinished_req → cache_unfinished_req`) does not re-match the tree, so `req.last_node` is still `None`. `cache_unfinished_req` then calls `dec_lock_ref(req.last_node)` unguarded, which dereferences `node.lock_ref` and raises `AttributeError: 'NoneType' object has no attribute 'lock_ref'`. The exception escapes the decode scheduler loop and kills the scheduler process — the engine keeps accepting requests but produces no tokens. `cache_finished_req` already guards this; `cache_unfinished_req` did not. The path was introduced in #19746.

## Modifications

**Commit 1 — guard.** Mirror the `cache_finished_req` guard in `cache_unfinished_req`: skip `dec_lock_ref` when `req.last_node is None` (nothing to release), and lock the newly matched node as before.

**Commit 2 — radix-aware resume (partial KV restore).** When the decode radix cache is enabled and the KV pool supports partial CPU restore, `resume_retracted_reqs()`:
- re-matches the radix tree and locks the device-resident prefix (`_match_prefix_and_lock`);
- pre-allocates with `total_prefix_len == prefix_len` (no HiCache loadback gap);
- restores only the `[prefix_len, seqlen-1)` suffix from the CPU offload copy via `load_kv_cache(start=prefix_len)`;
- releases the lock (`dec_lock_ref`) on a no-fit early-exit so `lock_ref` stays balanced.

`load_cpu_copy()` gains a `start` offset honored by the MHA (token-indexed), MLA, and DSA (page-indexed `index_k`) pools, via a shared `_restore_suffix_slice()` helper. A `support_partial_cpu_restore` capability flag (default `False` on the `KVCache` base; `True` on MHA and MLA, inherited by DSA) gates the path.

## Pools without partial-restore support are safe by design

Any pool that doesn't advertise `support_partial_cpu_restore` takes the existing full-restore path, unchanged:
- **No crash** — the `cache_unfinished_req` None-guard covers the resume case on either path.
- **No correctness gap** — full restore reconstructs the whole sequence from the CPU copy, as today.
- **Only a transient memory effect** — if the prefix is also resident in the tree, full restore briefly double-allocates it; the radix cache's existing dedup reclaims the duplicate on the next step (`cache_finished_req` / `cache_unfinished_req` free `kv_indices[cache_protected_len : prefix_len]` after `insert()`). One-step over-allocation, never a leak. The partial path avoids the duplication up front for opted-in pools.

## Accuracy Tests

Unit — `test/registered/unit/mem_cache/test_decode_radix_lock_ref.py`: **10 passed**. Includes the guard regression (`test_retracted_request_unfinished_none_last_node`, which fails without the guard with the exact `AttributeError` and passes with it) plus `TestRadixAwareResume` covering the resume control flow (match/lock, partial pre-alloc, suffix-only restore, `dec_lock_ref` on no-fit, and full-restore fallback when the pool lacks partial-restore support).

End-to-end on PD-disaggregated decode + decode radix cache with retraction forced deterministically (`SGLANG_TEST_RETRACT=1`), exercised across all three opt-in pool layouts — **MHA, MLA, and DSA** (including the page-indexed `index_k` path):
- **No crash, no leak:** zero `AttributeError … lock_ref`, zero `pool memory leak detected`, balanced `lock_ref` at graceful shutdown.
- **Correctness:** under greedy decoding, forcing retract+resume matches a no-retraction reference; the only run-to-run differences are batch-order nondeterminism at near-tied logits (confirmed with retraction off/on controls).
- **Reuse engaged:** resumed requests take the partial-restore path (`0 < prefix_len < fill`), every restore offset page-aligned.
- A large real-traffic replay (long, prefix-sharing requests) ran clean through hundreds of resume events with no faults.

## Speed Tests and Profiling

No measurable overhead: the guard is a single null-check, and the resume path replaces a full re-allocation + full CPU restore with a matched-prefix reuse + suffix-only restore (strictly less copy work when a prefix is reused).

## Checklist

- [x] Format code with pre-commit (ruff / black / isort / codespell).
- [x] Add unit tests.
- [ ] Update documentation (n/a — no user-facing API change).
- [x] Provide accuracy results (above); no speed regression.
- [x] Follow SGLang code style

---
### CI States

Latest PR Test (Base): :no_entry_sign: [Run #30687315134](https://github.com/sgl-project/sglang/actions/runs/30687315134)
Latest PR Test (Extra): :x: [Run #30687315014](https://github.com/sgl-project/sglang/actions/runs/30687315014)

### CODE REVIEW

**Comment by ronhuafeng** [comment]
Validated current head (`3aec28c81af1a89c18a5b5a1c0fc1f04b1001aee`).

Checks run locally:

```bash
git diff --check HEAD^..HEAD
python3 -m py_compile \
  python/sglang/srt/mem_cache/radix_cache.py \
  test/registered/unit/mem_cache/test_decode_radix_lock_ref.py
pre-commit run --files \
  python/sglang/srt/mem_cache/radix_cache.py \
  test/registered/unit/mem_cache/test_decode_radix_lock_ref.py
PYTHONPATH=python python3 -m pytest \
  test/registered/unit/mem_cache/test_decode_radix_lock_ref.py -q
```

Results: all passed; focused pytest in `lmsysorg/sglang:latest` reported `7 passed`.

I also ran a focused H200 runtime smoke with the PR head mounted into `lmsysorg/sglang:latest` (PyTorch `2.11.0+cu130`, CUDA `13.0`):

- 2 x H200
- model `Qwen/Qwen2.5-0.5B-Instruct`
- PD-disaggregated prefill/decode
- decode side `--disaggregation-decode-enable-radix-cache`
- `mooncake_tcp` transfer backend
- 4 clients x 3 rounds, 384-token request length, 64-token output length

Result without deterministic retraction: passed (`1 passed`), cache hits were observed (`5,376 / 9,984` prompt tokens cached overall), and post-workload health checks for the load balancer, prefill worker, and decode worker returned 200.

For transparency, I also tried the same smoke with deterministic retraction enabled (`SGLANG_TEST_RETRACT=true`, interval `3`) on both the PR head and the parent commit (`073de150530ab27e0646492ec00016c727f0d7f7`). Both runs failed with the same decode-side invariant:

```text
ValueError: pool memory leak detected! [full] ... evictable=1792, protected=0, session_held=0, uncached=0
```

I did not see the `AttributeError: 'NoneType' object has no attribute 'lock_ref'` signature in that stress run, so I would not treat it as a regression from this PR. It looks like a neighboring deterministic-retract cleanup issue that still needs follow-up/full PD workload validation.

Current GitHub `lint` is green; the red checks I saw are PR gate/skipped-test finish paths rather than a concrete failing test from this change.

**Review by ShangmingCai — APPROVED** [review]
LGTM.

CC: @hzh0425

File: python/sglang/srt/mem_cache/radix_cache.py [hunk 1]
```diff
@@ -541,7 +541,12 @@ def cache_unfinished_req(self, req: Req, chunked=False):
         # So we introduce this `cache_protected_len` field to make sure the partial part can be freed correctly.
         req.cache_protected_len = len(new_indices)
 
-        self.dec_lock_ref(req.last_node)
+        # `req.last_node` is None when the request was retracted: reset_for_retract()
+        # clears it, and the decode prebuilt path resumes via cache_unfinished_req
+        # without re-matching the tree, so there is no previous node to release here.
+        # cache_finished_req already guards this; mirror it to avoid dereferencing None.
```
Comment (hzh0425) [inline python/sglang/srt/mem_cache/radix_cache.py:550]: The `None` guard is still reasonable as defensive hardening, but the real fix should make the retracted resume path follow the same match/lock/allocation contract as normal PD decode preallocation.

A more complete fix would be:

1. In `resume_retracted_reqs()`, when `disaggregation_decode_enable_radix_cache` is enabled, call `_match_prefix_and_lock(req)` before `_pre_alloc`.
2. ...

**Review by hzh0425 — CHANGES_REQUESTED** [review]

**Comment by HsuYenMin** [comment]
[Update]

After digging into the resume path, the radix-aware fix needs a design decision (CPU-copy-authoritative vs. HiCache load_back for the `[prefix_len, total_prefix_len)` gap) plus a partial-restore change to `load_kv_cache`, which I'd want to validate on real PD-disagg hardware. Since this PR fixes a recurring production crash and the guard stays valid as hardening regardless, I've proposed (in the review thread above) landing the guard as the minimal crash-fix and taking the radix-aware resume as a tracked follow-up. Plan steps 1–2 below still hold for that follow-up.

---

Thanks @hzh0425 , that makes sense.

Confirming the plan for `resume_retracted_reqs()` (gated on `disaggregation_decode_enable_radix_cache`):

1. Call `_match_prefix_and_lock(req)` before `_pre_alloc`, and pass the resulting `prefix_indices` / `prefix_len` / `total_prefix_len into _pre_alloc(...)` (today it calls `_pre_alloc(req)` with no prefix args, so the retracted req re-allocates from scratch and `last_node` stays `None`).
2. Mirror `pop_preallocated`'s lock bookkeeping on the early-exit paths — `dec_lock_ref(req.last_node)` when a matched `req` doesn't fit and we break/skip — so `lock_ref` stays balanced.

Please let me know if that differs from the steps you had in mind. Want to make sure I match your intended contract, especially around the HiCache `total_prefix_len` loadback gap and the SWA tail-prealloc budget.

File: python/sglang/srt/mem_cache/radix_cache.py (hunk 1 above)
Comment (HsuYenMin) [reply python/sglang/srt/mem_cache/radix_cache.py:550]: Thanks @hzh0425, I took a further look and have two questions on the resume path:

1. The retract path keeps a full per-request CPU copy (`offload_kv_cache` to `kv_cache_cpu`). When `decode_prefix_len > l1_prefix_len`, should the resumed `req` restore the `[prefix_len, total_prefix_len)` gap from that CPU copy (CPU copy authoritative, skip HiCache loadback), or restore only `[total_prefix_len, …)` and let HiCache `load_back` fill the gap like `pop_preallocated`? This is the main fork in the implementation.
2. With the radix-aware path, `load_kv_cache` needs to become a partial restore (suffix only) so it doesn't overwrite the matched/locked prefix pages — does that match your intent?

Given
* this is a recurring production crash today
* the guard mirrors the existing cache_finished_req check and stays valid as hardening even after the deeper fix, and 
* the radix-aware resume is really the [TODO(retraction)](https://github.com/sgl-project/sglang/blob/073de150530ab27e0646492ec00016c727f0d7f7/python/sglang/srt/disaggregation/decode.py#L1319-L1321) refactor with the design choice above + a partial-restore change that I'd want to validate on real PD-disagg hardware

Would you be open to landing this guard as the minimal crash-fix, and I take the radix-aware resume as a tracked follow-up? I'll open an issue referencing the TODO(retraction) and the design, and implement it with your guidance on (1)/(2). Happy to go either way — just want to stop the crash promptly without rushing the larger change.

**Comment by hzh0425** [comment]
> [Update]
> 
> After digging into the resume path, the radix-aware fix needs a design decision (CPU-copy-authoritative vs. HiCache load_back for the `[prefix_len, total_prefix_len)` gap) plus a partial-restore change to `load_kv_cache`, which I'd want to validate on real PD-disagg hardware. Since this PR fixes a recurring production crash and the guard stays valid as hardening regardless, I've proposed (in the review thread above) landing the guard as the minimal crash-fix and taking the radix-aware resume as a tracked follow-up. Plan steps 1–2 below still hold for that follow-up.
> 
> Thanks @hzh0425 , that makes sense.
> 
> Confirming the plan for `resume_retracted_reqs()` (gated on `disaggregation_decode_enable_radix_cache`):
> 
> 1. Call `_match_prefix_and_lock(req)` before `_pre_alloc`, and pass the resulting `prefix_indices` / `prefix_len` / `total_prefix_len into _pre_alloc(...)` (today it calls `_pre_alloc(req)` with no prefix args, so the retracted req re-allocates from scratch and `last_node` stays `None`).
> 2. Mirror `pop_preallocated`'s lock bookkeeping on the early-exit paths — `dec_lock_ref(req.last_node)` when a matched `req` doesn't fit and we break/skip — so `lock_ref` stays balanced.
> 
> Please let me know if that differs from the steps you had in mind. Want to make sure I match your intended contract, especially around the HiCache `total_prefix_len` loadback gap and the SWA tail-prealloc budget.

I think this guard is useful as defensive hardening, but it should not be considered the real fix.

Can you directly fix in this pr?

File: python/sglang/srt/mem_cache/radix_cache.py (hunk 1 above)
Comment (HsuYenMin) [reply python/sglang/srt/mem_cache/radix_cache.py:550]: Hi @hzh0425,  @ShangmingCai,
radix-aware resume is now in as a second commit (70339467) on top of the guard, rebased on current main. Please take a look.

**Comment by HsuYenMin** [comment]
Hi @hzh0425,
Please feel free to provide feedback to this updated PR, and let me know if there's anything missing!
