### ISSUE TITLE
[Bug] 0.5.20: `--quantization humming` crashes at weight load — `BlockQuantScaleParameter` has no attribute `format_ue8m0`

### ISSUE THREAD

**Issue by c4bbage** [sgl-project/sglang#40393]
## Describe the bug

On v0.5.20, serving a DeepSeek-family / GLM MLA checkpoint with `--quantization humming` crashes at the end of weight loading on every TP rank:

```
File "sglang/srt/models/deepseek_common/deepseek_weight_loader.py", line 632, in post_load_weights
    weight_scale.format_ue8m0 and weight_scale.dtype == torch.uint8
AttributeError: 'BlockQuantScaleParameter' object has no attribute 'format_ue8m0'
```

The same command works on v0.5.19, and on v0.5.20 with `--quantization w4afp8`.

## Root cause

#38446 hoisted the attribute read out of a short-circuit expression:

- v0.5.19: `if should_deepgemm_weight_requant_ue8m0(...) and weight_scale.format_ue8m0:` — for humming the first operand is False, so `format_ue8m0` is never read.
- v0.5.20: `is_ue8m0_uint8 = (weight_scale.format_ue8m0 and weight_scale.dtype == torch.uint8)` — evaluated unconditionally.

`format_ue8m0` is stamped only by specific quant methods / MoE runners (`layers/quantization/fp8.py`, `moe/moe_runner/flashinfer_trtllm.py`, `moe/mega_moe.py`, the NPU methods). `layers/quantization/humming.py` never stamps it (`grep -c format_ue8m0 layers/quantization/humming.py` → 0), so the attribute genuinely does not exist on the kv_b_proj scale parameter.

## Suggested fix

Use the defaulted read, as `models/qwen3_5.py:528` already does:

```python
is_ue8m0_uint8 = (
    getattr(weight_scale, "format_ue8m0", False) and weight_scale.dtype == torch.uint8
)
```

(The same consideration applies to `fp8_utils.py:1562`, which already uses `getattr(..., False)`.)

## Reproduction

```
python3 -m sglang.launch_server --model-path <GLM-5.3-W4AFP8 checkpoint> \
  --tp 8 --quantization humming --moe-runner-backend humming \
  --disable-shared-experts-fusion --kv-cache-dtype fp8_e4m3 --trust-remote-code
```

## Environment

- SGLang v0.5.20 (image `lmsysorg/sglang:v0.5.20-cu130`), torch 2.13.0+cu130
- 8x H100 80GB and 8x H20 96GB, driver 570/590 series
- Reproduced on 3 machines (1 prefill + 2 decode of a PD deployment); each enters a crash-restart loop.

**Comment by c4bbage** [comment]
Additional context on the deployment shape, since the original report did not say where this shows up.

**Where we hit it:** a PD-disaggregated (prefill/decode) deployment of GLM-5.3-W4AFP8 — 1 prefill node + 2 decode nodes, `--disaggregation-transfer-backend mooncake`, TP8 on each node, `--kv-cache-dtype fp8_e4m3`, 256K context. Prefill runs on 8x H100 80GB, both decode nodes on 8x H20 96GB.

Full flag set on the decode nodes (prefill differs only in `--disaggregation-mode prefill` plus prefill-side chunking/HiCache flags):

```
python3 -m sglang.launch_server \
  --model-path <GLM-5.3-W4AFP8> --served-model-name GLM-5.3 --tp 8 --trust-remote-code \
  --quantization humming --moe-runner-backend humming --disable-shared-experts-fusion \
  --speculative-draft-model-quantization w4afp8 --speculative-moe-runner-backend auto \
  --kv-cache-dtype fp8_e4m3 --context-length 256000 \
  --disaggregation-transfer-backend mooncake --disaggregation-mode decode \
  --speculative-algorithm NEXTN --speculative-num-steps 4 --speculative-eagle-topk 1 \
  --speculative-num-draft-tokens 5 --dsa-decode-backend flashmla_kv --enable-symm-mem \
  --mem-fraction-static 0.85 --reasoning-parser glm45 --tool-call-parser glm47
```

**Impact in this shape:** all three nodes fail identically, during `post_load_weights`, on whichever TP rank reaches it first (we saw TP0, TP2 and TP5 across restarts). With `--restart unless-stopped` each node enters a crash-restart loop, and because every node of the PD chain runs the same image, there is no partial-service fallback — the whole chain is down until the image is rolled back.

**Scoping evidence, so this is not mistaken for a checkpoint or an AMD-only problem:**

- Same command, same checkpoint, same machines on **v0.5.19** — loads and serves normally.
- **v0.5.20** with `--quantization w4afp8` on the same checkpoint and machines — loads and serves normally (`max_total_num_tokens=442,240`). So the checkpoint is fine; only the `humming` quantization path is affected.
- The crash is on `kv_b_proj`, an **attention** linear, so `--moe-runner-backend humming` and `--disable-shared-experts-fusion` are not involved — `--quantization humming` alone selects the method that creates the unstamped `BlockQuantScaleParameter`.
- `grep -c format_ue8m0 python/sglang/srt/layers/quantization/humming.py` → `0`, versus 10 stamping sites in `fp8.py`.
- The change came in with #38446, which is titled as a gfx94x (AMD) fix; the breakage is on CUDA H100/H20, so the release-note category may hide it from other users hitting the same thing.

**Comment by c4bbage** [comment]
Opened a minimal fix for this: #40397 — reads the attribute with `getattr(weight_scale, "format_ue8m0", False)`, matching what `models/qwen3_5.py:528` and `layers/quantization/fp8_utils.py:1562` already do.
