### PR TITLE
[AMD] Fix Handle missing rope_theta in get_rope_config for Grok-1

### PR DESCRIPTION
**Pull request by michaelzhang-ai**
## Motivation

The AMD nightly CI jobs `nightly-8-gpu-grok1-int4` and `nightly-8-gpu-mi35x-grok1-int4` both crash during Grok-1 model loading with:

```
AttributeError: 'Grok1Config' object has no attribute 'rope_theta'
```

This was introduced in #21135, which migrated `grok.py` from a safe `getattr(config, "rope_theta", 10000)` to the shared `get_rope_config(config)` helper. However, the Grok-1 INT4 model (`amd/grok-1-W4A8KV8`) uses a custom `Grok1Config` class (via `trust_remote_code`) that does **not** define `rope_theta` — neither in `config.json` nor in `configuration_grok1.py` — so `get_rope_config()` raises `AttributeError` on the v4 fallback path (`config.rope_theta`).

**Why Grok-1 FP8 passes on the same commit:** The FP8 test uses `lmzheng/grok-1` which has `model_type: "mixtral"`, so transformers loads it as `MixtralConfig` which defines `rope_theta` as a default class attribute. The INT4 model uses `model_type: "grok-1"` → custom `Grok1Config` → no `rope_theta`.

| Model | `model_type` | Config class | Has `rope_theta`? |
|-------|-------------|-------------|-------------------|
| `lmzheng/grok-1` (FP8) | `mixtral` | `MixtralConfig` | Yes (class default) |
| `amd/grok-1-W4A8KV8` (INT4) | `grok-1` | custom `Grok1Config` | **No** |

CI failure links:
- Nightly #660 (commit bda94fc): [MI300X](https://github.com/sgl-project/sglang/actions/runs/23715102673/job/69080824526), [MI35x](https://github.com/sgl-project/sglang/actions/runs/23715102673/job/69080824541)
- Nightly #651 (commit 0906e45): [MI300X](https://github.com/sgl-project/sglang/actions/runs/23609617864/job/68761594419), [MI35x](https://github.com/sgl-project/sglang/actions/runs/23609617864/job/68761594393)

## Modifications

**`grok.py` only** — replaces the `get_rope_config()` call with local rope_theta extraction that:
1. Tries `config.rope_theta` via `getattr` (v4 path)
2. Falls back to `config.rope_parameters["rope_theta"]` if available (v5 path)
3. Defaults to `10000` if neither exists

This restores the exact behavior from before #21135 while still supporting transformers v5 `rope_parameters`.

## Scope — no NVIDIA / common code impact

- **Only `grok.py` changed** — the 42 other model files using `get_rope_config()` are untouched
- **Grok-1 is AMD-only** — model `amd/grok-1-W4A8KV8` has no NVIDIA CI tests; no NVIDIA code path is affected
- **Grok-1 FP8 unaffected** — uses `MixtralConfig` which already has `rope_theta`; passes on the same commit
- **Grok-2 unaffected** — uses a different model file, not `grok.py`; passes in nightly #660

## Verification

Triggered `nightly-8-gpu-grok1-int4` on this branch — **passed**:
- https://github.com/sgl-project/sglang/actions/runs/23633593801

## Checklist
- [x] Format your code according to the [Contribution Guide](https://docs.sglang.ai/references/contribution_guide.html)
- [x] Add unit tests for any new functionality where applicable
- [x] Update documentation if this PR changes any user-facing behavior

### CODE REVIEW

**Review by yctseng0211 — APPROVED** [review]

**Comment by michaelzhang-ai** [comment]
no NVIDIA / common code impact

1. Only grok.py changed — the 42 other model files using get_rope_config() are untouched
2. Grok-1 is AMD-only — model amd/grok-1-W4A8KV8 has no NVIDIA CI tests; no NVIDIA code path is affected
3. Grok-1 FP8 unaffected — uses MixtralConfig which already has rope_theta; passes on the same commit
4. Grok-2 unaffected — uses a different model file, not grok.py; passes in nightly https://github.com/sgl-project/sglang/pull/660

@HaiShaw
