### PR TITLE
update sgl-kernel 0.0.4.post2 for srt_hip

### PR DESCRIPTION
**Pull request by zhyncs**
## Checklist

- [ ] Format your code according to the [Code Formatting with Pre-Commit](https://docs.sglang.ai/references/contribution_guide.html#code-formatting-with-pre-commit).
- [ ] Add unit tests as outlined in the [Running Unit Tests](https://docs.sglang.ai/references/contribution_guide.html#running-unit-tests-adding-to-ci).
- [ ] Update documentation / docstrings / example tutorials as needed, according to [Writing Documentation](https://docs.sglang.ai/references/contribution_guide.html#writing-documentation-running-docs-ci).
- [ ] Provide throughput / latency benchmark results and accuracy evaluation results as needed, according to [Benchmark and Profiling](https://docs.sglang.ai/references/benchmark_and_profiling.html) and [Accuracy Results](https://docs.sglang.ai/references/accuracy_evaluation.html).
- [ ] For reviewers: If you haven't made any contributions to this PR and are only assisting with merging the main branch, please remove yourself as a co-author when merging the PR.
- [ ] Please feel free to join our Slack channel at https://slack.sglang.ai to discuss your PR.

### CODE REVIEW

**Comment by zhyncs** [comment]
fix https://github.com/sgl-project/sglang/actions/runs/13770802076/job/38508662777?pr=4215

**Comment by hebiao064** [comment]
Thanks!

**Review by hebiao064 — APPROVED** [review]

**Comment by zhyncs** [comment]
wait for https://github.com/sgl-project/sglang/actions/runs/13771668237?pr=4271

**Comment by zhyncs** [comment]
https://github.com/sgl-project/sglang/actions/runs/13771668237/job/38511502474?pr=4271

```
[2025-03-10 18:13:02 TP0] Failed to import from custom_ar with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory')
```
custom ar failed on AMD with v0.0.4.post1 @merrymercy

**Comment by yiakwy-xpu-ml-framework-team** [comment]
> https://github.com/sgl-project/sglang/actions/runs/13770802076/job/38508662777?pr=4215

WIP

**Comment by yiakwy-xpu-ml-framework-team** [comment]
cc @merrymercy related to **common_ops** introduced in commit https://github.com/sgl-project/sglang/pull/4213:

截屏2025-03-11 12 55 54

#### Note

unit tests in ROCm platform also failed due to lack of ROCM version support in this release :

```
>       return self._op(*args, **(kwargs or {}))
E       RuntimeError: moe_align_block_size kernel only support deepseek v3 now.

>               raise AttributeError(
                    f"'_OpNamespace' '{self.name}' object has no attribute '{op_name}'"
                )
E               AttributeError: '_OpNamespace' 'sgl_kernels' object has no attribute 'sgl_per_token_group_quant_fp8'
...
```

Let me give a comprehensive fix study (yes we have some PRs for the ops with ROCM support pending).


#### FIX ACTION

- enable `REGISTER_EXTENSION(common_ops)` in `torch_extension_rocm.cc` update `setup_rocm.py`

- make sure **srt_hip** with version updated with sgl-kernel (otherwise it will unstall rocm build and install cuda version from pip sources)

- rename **sgl_kernel-0.0.4.post2** to **sgl_kernel-0.0.4.post2[rocm]** , otherwise cuda version will be requested instead

```
# gfx942 
Installed /usr/local/lib/python3.12/dist-packages/sgl_kernel-0.0.4.post1-py3.12-linux-x86_64.egg
Processing dependencies for sgl-kernel==0.0.4.post1
Finished processing dependencies for sgl-kernel==0.0.4.post1
Python 3.12.8 (main, Dec  4 2024, 08:54:12) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from sgl_kernel import common_ops
>>> from sgl_kernel.allreduce import *
>>> import sgl_kernel
>>> dir (sgl_kernel)
['List', 'Tuple', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'all_reduce_reg', 'all_reduce_unreg', 'allocate_meta_buffer', 'allreduce', 'apply_rope_with_cos_sin_cache_inplace', 'attention', 'bmm_fp8', 'build_tree_kernel', 'build_tree_kernel_efficient', 'common_ops', 'ctypes', 'cublas_grouped_gemm', 'dispose', 'elementwise', 'fp8_blockwise_scaled_mm', 'fp8_scaled_mm', 'fused_add_rmsnorm', 'gelu_and_mul', 'gelu_tanh_and_mul', 'gemm', 'gemma_fused_add_rmsnorm', 'gemma_rmsnorm', 'get_graph_buffer_ipc_meta', 'get_meta_buffer_ipc_handle', 'init_custom_ar', 'int8_scaled_mm', 'lightning_attention_decode', 'meta_size', 'min_p_sampling_from_probs', 'moe', 'moe_align_block_size', 'os', 'register_buffer', 'register_graph_buffers', 'rmsnorm', 'sampling', 'sgl_per_tensor_quant_fp8', 'sgl_per_token_group_quant_fp8', 'sgl_per_token_quant_fp8', 'silu_and_mul', 'speculative', 'top_k_renorm_prob', 'top_k_top_p_sampling_from_probs', 'top_p_renorm_prob', 'top_p_sampling_from_probs', 'torch', 'tree_speculative_sampling_target_only', 'utils', 'version']
>>> 
```

##### verificiation after fix

supported ops:

- sgl-kernel/tests/test_moe_align.py
截屏2025-03-11 15 29 43

- test/srt/test_mla.py

##### e2e test

- DeepSeek V3 (passed with sglang==0.4.3.post4, sgl-kernel==0.0.4.post, 1507.501 token/s, default --max-concurrency) :
 
截屏2025-03-11 16 19 11

```
# server
HSA_NO_SCRATCH_RECLAIM=1 python3 -m sglang.launch_server --model /data/yiakwy/WorkSpace/Github/models/DeepSeek-V3/ --tp 8 --trust-remote-code

# client
python benchmark/gsm8k/bench_sglang.py --num-questions 2000 --parallel 2000 --num-shots 8
```

**Comment by yiakwy-xpu-ml-framework-team** [comment]
After update `sgl-kernel-0.0.4.post1` to `sgl-kernel-0.0.4.post2` and do slang install, I found

```
    Found existing installation: sgl-kernel 0.0.4.post2
    Uninstalling sgl-kernel-0.0.4.post2:
      Successfully uninstalled sgl-kernel-0.0.4.post2
  Attempting uninstall: xgrammar
    Found existing installation: xgrammar 0.1.14
    Uninstalling xgrammar-0.1.14:
      Successfully uninstalled xgrammar-0.1.14
Successfully installed sgl-kernel-0.0.4.post1 sglang-0.4.3.post4 xgrammar-0.1.15
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python3.12 -m pip install --upgrade pip
➜  /workspace git:(zhyncs/amd) ✗ python
Python 3.12.8 (main, Dec  4 2024, 08:54:12) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sglang
>>> import sgl_kernel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/dist-packages/sgl_kernel/__init__.py", line 12, in <module>
    from sgl_kernel import common_ops
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
>>>
```

I guess sglang installer forced uninstall my rocm build sgl-kernel and , reinstall cuda sgl-kernel:

> srt_hip = ["sglang[runtime_common]", "sgl-kernel==0.0.4.post1", "torch", "vllm==0.6.7.dev2", "outlines==0.1.11"]

to 

> srt_hip = ["sglang[runtime_common]", "sgl-kernel==0.0.4.post2[rocm]", "torch", "vllm==0.6.7.dev2", "outlines==0.1.11"]

**Comment by zhyncs** [comment]
Thanks @yiakwy-xpu-ml-framework-team for the quick fix!

File: .github/workflows/pr-test-amd.yml [hunk 1]
```diff
@@ -46,6 +48,7 @@ jobs:
         run: |
           docker exec ci_sglang pip install --upgrade pip
           docker exec -w /sglang-checkout/sgl-kernel ci_sglang python3 setup_rocm.py install
+          docker exec -w /sglang-checkout/sgl-kernel ci_sglang pip uninstall sgl-kernel -y
```
Comment (zhyncs) [inline .github/workflows/pr-test-amd.yml:50]:
```suggestion
```
