### ISSUE TITLE
[Bug] AttributeError: 'Fp8MoEMethod' object has no attribute 'moe_runner_config' when using flashinfer_trtllm_routed MoE backend with speculative decoding (DSPARK/EAGLE) on hybrid NVFP4 checkpoints

### ISSUE THREAD

**Issue by shyeh25** [sgl-project/sglang#36264]
### Checklist

- [x] I searched related issues but found no solution.
- [x] The bug persists in the latest version.
- [x] Issues without environment info and a minimal reproducible demo are hard to resolve and may receive no feedback.
- [x] If this is not a bug report but a general question, please start a discussion at https://github.com/sgl-project/sglang/discussions. Otherwise, it will be closed.
- [x] Please use English. Otherwise, it will be closed.

### Describe the bug

When serving a hybrid NVFP4 checkpoint (main MoE experts quantized to NVFP4 via
`ModelOptNvFp4FusedMoEMethod`, with a bundled draft/MTP head excluded from NVFP4 quantization
and falling back to fp8) with `--moe-runner-backend flashinfer_trtllm_routed` (or
`flashinfer_trtllm`) **and speculative decoding enabled** (reproduced with both `DSPARK` and
`EAGLE`), the server crashes on startup with:

AttributeError: 'Fp8MoEMethod' object has no attribute 'moe_runner_config'

This is a regression introduced by #33962 ("enable TRT-LLM for MiniMax M3 by preserving SwiGLU
params"), which added `Fp8MoEMethod._prepare_flashinfer_trtllm_activation_params()` reading
`self.moe_runner_config`. That attribute is only ever set inside `Fp8MoEMethod.create_moe_runner()`
when the method constructs and **owns** its own `MoeRunner`. However, `Fp8MoEMethod` is also used
as an internal delegate (`self._fp8`) by `Mxfp4FlashinferTrtllmMoEMethod` (introduced in #25820)
to handle the fp8-fallback layers (e.g. the excluded draft/MTP head in a hybrid NVFP4 checkpoint).
`Mxfp4FlashinferTrtllmMoEMethod.create_moe_runner()` never forwards `moe_runner_config` to the
delegate's `create_moe_runner()`, so when the delegate's `process_weights_after_loading()` is
later invoked and hits the new `_prepare_flashinfer_trtllm_activation_params()` call, `self.moe_runner_config`
was never set → crash.

This bug existed dormant since #25820 (2026-06-21) and only became reachable once #33962
(2026-08-09) added the new attribute access — before that, `Fp8MoEMethod.process_weights_after_loading()`
never touched `self.moe_runner_config` at all when used as a delegate.

### Reproduction

# Reproduction
Any hybrid NVFP4 checkpoint with a bundled/excluded fp8-fallback MoE layer (in our case: a
DSPARK/MTP draft head) + `flashinfer_trtllm_routed` backend + speculative decoding enabled will
trigger this deterministically at server startup, right after weight loading completes. This is
easily reproducible using the same public checkpoint and command @mmangkad used to validate
DSPark+NVFP4 loading in #33276 (merged before #33962 introduced this regression):

```bash
sglang serve \
  --model-path mmangkad/DeepSeek-V4-Flash-0731-NVFP4 \
  --moe-runner-backend flashinfer_trtllm_routed \
  --speculative-algorithm DSPARK \
  --reasoning-parser deepseek-v4 \
  --tool-call-parser deepseekv4 \
  --trust-remote-code
```

This combination worked correctly at the time of #33276 (2026-08-02, GSM8K acc=96.89%), but regressed after #33962 (2026-08-09) added the new moe_runner_config access.

Full traceback (captured on lmsysorg/sglang:nightly-dev-cu13-20260824-95f5ecd3):

```
[2026-08-24 20:51:37 TP3] Scheduler hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 5196, in run_scheduler_process
    scheduler = Scheduler(
                ^^^^^^^^^^
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 524, in __init__
    self.init_model_worker()
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1006, in init_model_worker
    self.maybe_init_draft_worker()
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 950, in maybe_init_draft_worker
    self.draft_worker = DraftWorkerClass(**draft_worker_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sgl-workspace/sglang/python/sglang/srt/speculative/dspark_components/dspark_worker_v2.py", line 126, in __init__
    bundle = build_draft_tp_worker(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/sgl-workspace/sglang/python/sglang/srt/speculative/draft_worker_common.py", line 80, in build_draft_tp_worker
    draft_worker = draft_worker_cls(
                   ^^^^^^^^^^^^^^^^^
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 344, in __init__
    self._init_model_runner()
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 473, in _init_model_runner
    self._model_runner = ModelRunner(
                         ^^^^^^^^^^^^
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 461, in __init__
    self.initialize()
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 655, in initialize
    self.load_model()
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1125, in load_model
    loaded = load_model_with_memory_saver(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner_components/load_model_utils.py", line 324, in load_model_with_memory_saver
    model = loader.load_model(
            ^^^^^^^^^^^^^^^^^^
  File "/sgl-workspace/sglang/python/sglang/srt/model_loader/loader.py", line 991, in load_model
    self.load_weights_and_postprocess(
  File "/sgl-workspace/sglang/python/sglang/srt/model_loader/loader.py", line 1064, in load_weights_and_postprocess
    quant_method.process_weights_after_loading(module)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/quantization/mxfp4_flashinfer_trtllm_moe.py", line 141, in process_weights_after_loading
    self._fp8.process_weights_after_loading(layer)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/quantization/fp8.py", line 2146, in process_weights_after_loading
    self._prepare_flashinfer_trtllm_activation_params(layer)
  File "/sgl-workspace/sglang/python/sglang/srt/layers/quantization/fp8.py", line 2159, in _prepare_flashinfer_trtllm_activation_params
    ("gemm1_alpha", self.moe_runner_config.gemm1_alpha),
                    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Fp8MoEMethod' object has no attribute 'moe_runner_config'
```

We independently reproduced the identical crash signature on a different model (DeepSeek-V4-Pro-NVFP4, EAGLE spec-decode, disaggregated P/D deployment) — same root cause, different checkpoint/model, confirming this is not model-specific.

# Bisect
nightly-dev-cu13-20260810-*: PASS (before #33962)
nightly-dev-cu13-20260811-* through nightly-dev-cu13-20260824-95f5ecd3: FAIL
Manually reverting #33962's fp8.py changes restores PASS on the 20260811 build.

# Suggested fix
`Fp8MoEMethod` should track whether *this instance* actually owns a constructed `MoeRunner`
(vs. being used only for its weight-loading/dequant helper methods as a borrowed delegate
inside `Mxfp4FlashinferTrtllmMoEMethod`), and gate `_prepare_flashinfer_trtllm_activation_params()`
on that ownership rather than a bare `get_moe_runner_backend().is_flashinfer_trtllm(_routed)()`
check — the bare backend check is true for *any* layer in the model when the backend is globally
selected, even for delegate instances that never got a `moe_runner_config`.

We are still running a full regression test suite against a candidate fix implementing this
(an explicit `_owned_moe_runner` field, set only when `create_moe_runner()` constructs its own
runner) and will follow up with a PR once complete.

### Environment

Container: lmsysorg/sglang:nightly-dev-cu13-20260824-95f5ecd3
GPU: NVIDIA GB300

**Comment by mmangkad** [comment]
Hi @shyeh25, thanks for reporting this. Do you have the PR ready now?

**Comment by shyeh25** [comment]
@mmangkad 
https://github.com/sgl-project/sglang/pull/36275 could solve this issue. Thanks @ActiveSky's effort.

**Comment by ActiveSky** [comment]
Hi @shyeh25 and @mmangkad,

Thank you both for your help with this issue. @shyeh25, thank you for reporting the problem and sharing the details. @mmangkad, thank you for following up and helping coordinate.

We have prepared PR #36275, which aims to address this issue and is ready for review:
https://github.com/sgl-project/sglang/pull/36275

Please feel free to let us know if any changes are needed. We’d be happy to update the PR.
